"""Create projects and pages.

Revision ID: cfbcb699274c
Revises:
Create Date: 2026-09-26 22:02:08.655296
"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = 'cfbcb699274c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('authors', sa.String(length=500), nullable=False),
        sa.Column('publisher', sa.String(length=500), nullable=False),
        sa.Column('publication_place', sa.String(length=200), nullable=False),
        sa.Column('publication_year', sa.String(length=200), nullable=False),
        sa.Column('edition', sa.String(length=200), nullable=False),
        sa.Column('series', sa.String(length=500), nullable=False),
        sa.Column('volume', sa.String(length=200), nullable=False),
        sa.Column('language', sa.String(length=200), nullable=False),
        sa.Column('orthography', sa.Enum('UNKNOWN', 'PRE_REFORM', 'MODERN', name='orthography'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=False),
        sa.Column('source_kind', sa.Enum('PDF', 'IMAGES', name='sourcekind'), nullable=True),
        sa.Column('source_name', sa.String(length=500), nullable=False),
        sa.Column('source_size_bytes', sa.Integer(), nullable=False),
        sa.Column('source_metadata', sa.JSON(), nullable=False),
        sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'pages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('index', sa.Integer(), nullable=False),
        sa.Column('source_file', sa.String(length=500), nullable=False),
        sa.Column('width_px', sa.Integer(), nullable=False),
        sa.Column('height_px', sa.Integer(), nullable=False),
        sa.Column('dpi_x', sa.Double(), nullable=True),
        sa.Column('dpi_y', sa.Double(), nullable=True),
        sa.Column('color_mode', sa.Enum('BILEVEL', 'GRAY', 'COLOR', 'UNKNOWN', name='colormode'), nullable=False),
        sa.Column('bits_per_component', sa.Integer(), nullable=True),
        sa.Column('image_format', sa.String(length=200), nullable=False),
        sa.Column('width_mm', sa.Double(), nullable=True),
        sa.Column('height_mm', sa.Double(), nullable=True),
        sa.Column('has_text_layer', sa.Boolean(), nullable=False),
        sa.Column('extra', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('project_id', 'index'),
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_project_id'))

    op.drop_table('pages')
    op.drop_table('projects')
    # ### end Alembic commands ###
