"""Add the pagination sections and mark the labels written by hand.

Revision ID: 075dd13dca68
Revises: 84993c1e790e
Create Date: 2026-10-03 14:51:46.739278
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import advanced_alchemy.types.json
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = '075dd13dca68'
down_revision: str | Sequence[str] | None = '84993c1e790e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pagination_sections',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('first_page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'style',
            sa.Enum(
                'arabic',
                'roman-lower',
                'roman-upper',
                'alpha-lower',
                'alpha-upper',
                'none',
                name='labelstyle',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('start', sa.Integer(), nullable=False),
        sa.Column('prefix', sa.String(), nullable=False),
        sa.Column(
            'display',
            sa.Enum('not-counted', 'counted', 'printed', name='numberdisplay', native_enum=False),
            nullable=False,
        ),
        sa.Column(
            'kinds',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['first_page_id'], ['pages.id'], name=op.f('fk_pagination_sections_first_page_id_pages'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_pagination_sections_project_id_projects'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pagination_sections')),
    )
    with op.batch_alter_table('pagination_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagination_sections_first_page_id'), ['first_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagination_sections_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_manual', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('label_manual')

    with op.batch_alter_table('pagination_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagination_sections_project_id'))
        batch_op.drop_index(batch_op.f('ix_pagination_sections_first_page_id'))

    op.drop_table('pagination_sections')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it.

    No book has a section yet, so every label that exists was written by hand or came with the scan. Each becomes an
    exception that a recompute of the numbers never changes, which keeps everything a person typed.
    """
    pages = sa.table('pages', sa.column('label', sa.String()), sa.column('label_manual', sa.Boolean()))
    op.execute(pages.update().where(sa.func.length(pages.c.label) > 0).values(label_manual=True))


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted.

    The labels stay as they are, since a page keeps the number it shows whether it was computed or written by hand.
    """
