"""Record the format of the full image.

A scan and a page version keep the format of their ``full`` image in ``renditions_full``, chosen when the image was
written, so a later change of the project's image policy never changes the storage key of a stored image. Every image
stored before this revision is a JPEG: a scan gets it from the server default of the column, and a page version that
has an image is set by ``data_upgrades``, while a version of a step without an image keeps a null.

Revision ID: 1d0fc6453df6
Revises: 6446f5ce697c
Create Date: 2026-09-30 16:32:15.763731
"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = '1d0fc6453df6'
down_revision: str | Sequence[str] | None = '6446f5ce697c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'renditions_full',
                sa.Enum(
                    'full.jpg', 'full.png', 'preview.jpg', 'thumb.jpg', 'iiif', name='rendition', native_enum=False
                ),
                nullable=True,
            )
        )

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'renditions_full',
                sa.Enum(
                    'full.jpg', 'full.png', 'preview.jpg', 'thumb.jpg', 'iiif', name='rendition', native_enum=False
                ),
                server_default='full.jpg',
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('renditions_full')

    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_column('renditions_full')

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""
    op.execute(sa.text("UPDATE page_versions SET renditions_full = 'full.jpg' WHERE renditions_ready IS NOT NULL"))


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
