"""Add the recipe profiles of the accounts.

Revision ID: 41146836448a
Revises: 13662fc5c17e
Create Date: 2026-10-03 01:05:45.233935
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import advanced_alchemy.types.json
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = '41146836448a'
down_revision: str | Sequence[str] | None = '13662fc5c17e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The identifier of an account, as the fastapi-users library declared it: CHAR(36) on SQLite and UUID on PostgreSQL
ACCOUNT_GUID = sa.CHAR(36).with_variant(postgresql.UUID(), 'postgresql')


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recipe_profiles',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('account_id', ACCOUNT_GUID, nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'steps',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_id'], ['user.id'], name=op.f('fk_recipe_profiles_account_id_user'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_profiles')),
    )
    with op.batch_alter_table('recipe_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_profiles_account_id'), ['account_id'], unique=False)
        batch_op.create_index(
            'ix_recipe_profiles_one_default',
            ['account_id', 'stage'],
            unique=True,
            sqlite_where=sa.text('is_default'),
            postgresql_where=sa.text('is_default'),
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_profiles', schema=None) as batch_op:
        batch_op.drop_index(
            'ix_recipe_profiles_one_default', sqlite_where=sa.text('is_default'), postgresql_where=sa.text('is_default')
        )
        batch_op.drop_index(batch_op.f('ix_recipe_profiles_account_id'))

    op.drop_table('recipe_profiles')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
