"""Let a change of the history of a step name the change it takes back.

Revision ID: 45e3f395141c
Revises: 53cae47541f2
Create Date: 2026-10-04 04:44:47.465446
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = '45e3f395141c'
down_revision: str | Sequence[str] | None = '53cae47541f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_step_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('undoes_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_page_step_changes_undoes_id'), ['undoes_id'], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_step_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_step_changes_undoes_id'))
        batch_op.drop_column('undoes_id')

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
