"""Add the processing tables and the columns of page versions and jobs.

A page stage keeps the current version of one stage of a page, a page edit a manual edit that a processor reads, and a
recipe the steps of a stage with one active recipe per stage, kept by a partial unique index. A page version gains the
scale of its run, the hash of its manual edit and whether its tile pyramid is cut, which every version that already has
its images is, since the images were cut with them, and a job gains the parameters of a processing job. The partial
unique index ``ix_jobs_one_active_processing`` keeps a project to one queued or running job of the kinds that
process the versions of its pages, so two runs never write the same files and a collection never deletes what a run
reuses.

Revision ID: 49e74cc886a4
Revises: d5b4c3cd9379
Create Date: 2026-10-01 08:35:46.750151
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# The rows of the partial unique index that keeps a project to one job processing the versions of its pages
ACTIVE_PROCESSING = sa.text(
    "kind IN ('collect-versions', 'cut-tiles', 'preview-step', 'run-stage') AND state IN ('queued', 'running')"
)

# Revision identifiers, used by Alembic
revision: str = '49e74cc886a4'
down_revision: str | Sequence[str] | None = 'd5b4c3cd9379'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recipes',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'steps',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_recipes_project_id_projects'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(
            'ix_recipes_one_active',
            ['project_id', 'stage'],
            unique=True,
            sqlite_where=sa.text('active'),
            postgresql_where=sa.text('active'),
        )
        batch_op.create_index('ix_recipes_project_id_stage', ['project_id', 'stage'], unique=False)

    op.create_table(
        'page_edits',
        sa.Column('page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('processor_key', sa.String(), nullable=False),
        sa.Column(
            'kind',
            sa.Enum(
                'none',
                'rect',
                'quad',
                'line',
                'rotation',
                'mesh',
                'brush-mask',
                'regions',
                name='editorkind',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'geometry',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=True,
        ),
        sa.Column('mask_key', sa.String(), nullable=True),
        sa.Column('edit_hash', sa.String(), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['page_id'], ['pages.id'], name=op.f('fk_page_edits_page_id_pages'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('page_id', 'stage', 'processor_key', name=op.f('pk_page_edits')),
    )
    op.create_table(
        'page_stages',
        sa.Column('page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('recipe_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('head_version_id', sa.String(length=16), nullable=True),
        sa.Column('state', sa.Enum('fresh', 'stale', 'failed', name='stagestate', native_enum=False), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['head_version_id'],
            ['page_versions.id'],
            name=op.f('fk_page_stages_head_version_id_page_versions'),
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['page_id'], ['pages.id'], name=op.f('fk_page_stages_page_id_pages'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['recipe_id'], ['recipes.id'], name=op.f('fk_page_stages_recipe_id_recipes'), ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('page_id', 'stage', name=op.f('pk_page_stages')),
    )
    with op.batch_alter_table('page_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_stages_head_version_id'), ['head_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_stages_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column(
            'kind',
            existing_type=sa.VARCHAR(length=13),
            type_=sa.Enum(
                'import-source',
                'prepare-pages',
                'run-stage',
                'preview-step',
                'cut-tiles',
                'collect-versions',
                name='jobkind',
                native_enum=False,
            ),
            existing_nullable=False,
        )
        batch_op.add_column(
            sa.Column(
                'params',
                sa.JSON()
                .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
                .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
                server_default='{}',
                nullable=False,
            )
        )
        batch_op.create_index(
            'ix_jobs_one_active_processing',
            ['project_id'],
            unique=True,
            sqlite_where=ACTIVE_PROCESSING,
            postgresql_where=ACTIVE_PROCESSING,
        )

    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'scale',
                sa.Enum('full', 'preview', name='versionscale', native_enum=False),
                server_default='full',
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column('edit_hash', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('tiles_ready', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_column('tiles_ready')
        batch_op.drop_column('edit_hash')
        batch_op.drop_column('scale')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(
            'ix_jobs_one_active_processing',
            sqlite_where=ACTIVE_PROCESSING,
            postgresql_where=ACTIVE_PROCESSING,
        )
        batch_op.drop_column('params')
        batch_op.alter_column(
            'kind',
            existing_type=sa.Enum(
                'import-source',
                'prepare-pages',
                'run-stage',
                'preview-step',
                'cut-tiles',
                'collect-versions',
                name='jobkind',
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=13),
            existing_nullable=False,
        )

    with op.batch_alter_table('page_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_stages_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_page_stages_head_version_id'))

    op.drop_table('page_stages')
    op.drop_table('page_edits')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index('ix_recipes_project_id_stage')
        batch_op.drop_index('ix_recipes_one_active', sqlite_where=sa.text('active'), postgresql_where=sa.text('active'))

    op.drop_table('recipes')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""
    # Every version stored before this revision is a base version, whose pyramid was cut with its other files
    op.execute(sa.text('UPDATE page_versions SET tiles_ready = renditions_ready WHERE renditions_ready IS TRUE'))


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
