"""Add the content type of a page.

Revision ID: 8cf44472edb6
Revises: d1bd087dadcc
Create Date: 2026-10-04 15:10:27.663023
"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = '8cf44472edb6'
down_revision: str | Sequence[str] | None = 'd1bd087dadcc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'content_type',
                sa.Enum('text', 'color-picture', 'bw-picture', name='contenttype', native_enum=False),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column('content_by_hand', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('content_by_hand')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
