"""Add the mark and the comment of a result and the log of their changes.

Revision ID: a8b6015ddb1b
Revises: 8cf44472edb6
Create Date: 2026-10-04 11:49:44.228798
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'a8b6015ddb1b'
down_revision: str | Sequence[str] | None = '8cf44472edb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'result_mark_changes',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('version_id', sa.String(length=16), nullable=False),
        sa.Column('mark_before', sa.Enum('good', 'bad', name='resultmark', native_enum=False), nullable=True),
        sa.Column('mark_after', sa.Enum('good', 'bad', name='resultmark', native_enum=False), nullable=True),
        sa.Column('comment_before', sa.String(), server_default='', nullable=False),
        sa.Column('comment_after', sa.String(), server_default='', nullable=False),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['version_id'],
            ['page_versions.id'],
            name=op.f('fk_result_mark_changes_version_id_page_versions'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_result_mark_changes')),
        sa.UniqueConstraint('version_id', 'sequence', name=op.f('uq_result_mark_changes_version_id')),
    )
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('mark', sa.Enum('good', 'bad', name='resultmark', native_enum=False), nullable=True)
        )
        batch_op.add_column(sa.Column('comment', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('mark')

    op.drop_table('result_mark_changes')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
