"""Add the values of the steps for the odd pages, the even pages and the groups.

A step may have a value of a field for the odd pages, for the even pages and for each group of pages, besides the
values of the pages themselves. They are kept once for the step in ``step_values``, and the history of a page names the
part of the pages a change of its settings was for.

The upgrade makes the table and the two columns of the history, which every existing change fills with the pages
themselves, and gives the changes the source ``reset`` made by the reset of steps, which no longer exists, the source of
the user. The downgrade drops the table and the columns, and the values of the parts of the pages go with them.

Revision ID: b8e258b21279
Revises: 77356245ed16
Create Date: 2026-10-08 07:45:31.091193
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'b8e258b21279'
down_revision: str | Sequence[str] | None = '77356245ed16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'step_values',
        sa.Column('step_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'scope', sa.Enum('pages', 'group', 'odd', 'even', name='valuescope', native_enum=False), nullable=False
        ),
        sa.Column('group_label', sa.String(), server_default='', nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'params',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            server_default='{}',
            nullable=False,
        ),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_step_values_project_id_projects'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('step_id', 'scope', 'group_label', name=op.f('pk_step_values')),
    )
    with op.batch_alter_table('step_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_values_project_id'), ['project_id', 'stage'], unique=False)

    with op.batch_alter_table('page_step_changes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'scope',
                sa.Enum('pages', 'group', 'odd', 'even', name='valuescope', native_enum=False),
                server_default='pages',
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column('group_label', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_step_changes', schema=None) as batch_op:
        batch_op.drop_column('group_label')
        batch_op.drop_column('scope')

    with op.batch_alter_table('step_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_values_project_id'))

    op.drop_table('step_values')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Give the changes made by a reset of steps the source of the user, since the reset is gone."""
    op.execute(sa.text("UPDATE page_step_changes SET source = 'user' WHERE source = 'reset'"))


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
