"""Drop the time a collection removed the files of a page version.

A collection now deletes the row of a version with its files, so no row keeps a picture that is gone, and the column
that told the two apart goes. A row whose files an earlier collection removed stays until the next collection, which
chooses it by the rule it chooses every other version by and deletes it, since its directory is gone already.

Revision ID: ba28fd6fb352
Revises: 7069c4fcf234
Create Date: 2026-10-08 18:19:02.311980
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'ba28fd6fb352'
down_revision: str | Sequence[str] | None = '7069c4fcf234'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_column('files_removed_at')

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('files_removed_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
