"""Create the baseline schema.

The tables of the book model (``projects``, ``jobs``, ``sources``, ``scans``, ``pages``, ``page_versions``) and the
account tables of fastapi-users (``user``, ``accesstoken``, ``oauth_account``), as autogenerate wrote them from the
models, with one change by hand: the cover key of ``projects`` is added after ``pages`` and dropped before it.

Revision ID: c9d68667dae1
Revises:
Create Date: 2026-09-30 10:09:12.458624
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import advanced_alchemy.types.json
import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'c9d68667dae1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table(
        'accesstoken',
        sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('token', sa.String(length=43), nullable=False),
        sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_accesstoken_user_id_user'), ondelete='cascade'),
        sa.PrimaryKeyConstraint('token', name=op.f('pk_accesstoken')),
    )
    with op.batch_alter_table('accesstoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accesstoken_created_at'), ['created_at'], unique=False)

    op.create_table(
        'oauth_account',
        sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('oauth_name', sa.String(length=100), nullable=False),
        sa.Column('access_token', sa.String(length=1024), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('refresh_token', sa.String(length=1024), nullable=True),
        sa.Column('account_id', sa.String(length=320), nullable=False),
        sa.Column('account_email', sa.String(length=320), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('fk_oauth_account_user_id_user'), ondelete='cascade'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_account')),
    )
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_account_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_account_oauth_name'), ['oauth_name'], unique=False)

    op.create_table(
        'projects',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('authors', sa.String(), nullable=False),
        sa.Column('publisher', sa.String(), nullable=False),
        sa.Column('publication_place', sa.String(), nullable=False),
        sa.Column('publication_year', sa.String(), nullable=False),
        sa.Column('edition', sa.String(), nullable=False),
        sa.Column('series', sa.String(), nullable=False),
        sa.Column('volume', sa.String(), nullable=False),
        sa.Column('language', sa.String(), nullable=False),
        sa.Column(
            'orthography',
            sa.Enum('unknown', 'pre-reform', 'modern', name='orthography', native_enum=False),
            nullable=False,
        ),
        sa.Column('notes', sa.String(), nullable=False),
        sa.Column(
            'image_policy', sa.Enum('compact', 'lossless', name='imagepolicy', native_enum=False), nullable=False
        ),
        sa.Column('cover_page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_projects_owner_id_user'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_updated_at'), ['updated_at'], unique=False)

    op.create_table(
        'jobs',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('kind', sa.Enum('import-source', name='jobkind', native_enum=False), nullable=False),
        sa.Column(
            'state',
            sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='jobstate', native_enum=False),
            nullable=False,
        ),
        sa.Column('progress_done', sa.Integer(), nullable=False),
        sa.Column('progress_total', sa.Integer(), nullable=False),
        sa.Column('error', sa.String(), nullable=False),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('started_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
        sa.Column('finished_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)

    op.create_table(
        'sources',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('kind', sa.Enum('pdf', 'djvu', 'image', name='sourcekind', native_enum=False), nullable=False),
        sa.Column(
            'file_type',
            sa.Enum('pdf', 'djvu', 'tiff', 'jpeg', 'jpeg-2000', 'png', name='filetype', native_enum=False),
            nullable=False,
        ),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column(
            'files',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('sha256', sa.String(), nullable=False),
        sa.Column('scan_count', sa.Integer(), nullable=False),
        sa.Column(
            'metadata',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'suggestion',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('import_job_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('imported_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['import_job_id'], ['jobs.id'], name=op.f('fk_sources_import_job_id_jobs'), ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_sources_project_id_projects'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
        sa.UniqueConstraint('project_id', 'sha256', name=op.f('uq_sources_project_id')),
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_project_id'), ['project_id'], unique=False)

    op.create_table(
        'scans',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('source_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('source_label', sa.String(), nullable=False),
        sa.Column('width_px', sa.Integer(), nullable=False),
        sa.Column('height_px', sa.Integer(), nullable=False),
        sa.Column(
            'color_mode',
            sa.Enum('bilevel', 'gray', 'color', 'unknown', name='colormode', native_enum=False),
            nullable=False,
        ),
        sa.Column('dpi_x', sa.Float(), nullable=True),
        sa.Column('dpi_y', sa.Float(), nullable=True),
        sa.Column('bits_per_component', sa.Integer(), nullable=True),
        sa.Column('image_format', sa.String(), nullable=False),
        sa.Column('width_mm', sa.Float(), nullable=True),
        sa.Column('height_mm', sa.Float(), nullable=True),
        sa.Column('has_text_layer', sa.Boolean(), nullable=False),
        sa.Column(
            'extra',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('renditions_ready', sa.Boolean(), nullable=False),
        sa.Column('renditions_version', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_scans_project_id_projects'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['source_id'], ['sources.id'], name=op.f('fk_scans_source_id_sources'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_scans')),
        sa.UniqueConstraint('source_id', 'number', name=op.f('uq_scans_source_id')),
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_project_id'), ['project_id'], unique=False)

    op.create_table(
        'pages',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('order_key', sa.String().with_variant(sa.String(collation='C'), 'postgresql'), nullable=False),
        sa.Column('label', sa.String(), nullable=False),
        sa.Column(
            'kind',
            sa.Enum(
                'cover',
                'back-cover',
                'endpaper',
                'frontispiece',
                'title',
                'text',
                'plate',
                'blank',
                'other',
                name='pagekind',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'origin', sa.Enum('scan', 'blank', 'placeholder', name='pageorigin', native_enum=False), nullable=False
        ),
        sa.Column('scan_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('slot', sa.Integer(), nullable=False),
        sa.Column('included', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.String(), nullable=False),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_pages_project_id_projects'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_pages_scan_id_scans'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
        sa.UniqueConstraint('project_id', 'order_key', name=op.f('uq_pages_project_id')),
        sa.UniqueConstraint('scan_id', 'slot', name=op.f('uq_pages_scan_id')),
    )
    # The cover key of a project refers to pages, which refer to projects, so it is added once pages exists.
    # Autogenerate renders it inside projects with use_alter, which PostgreSQL leaves out of CREATE TABLE
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_projects_cover_page_id_pages'), 'pages', ['cover_page_id'], ['id'], ondelete='SET NULL'
        )

    op.create_table(
        'page_versions',
        sa.Column('id', sa.String(length=16), nullable=False),
        sa.Column('page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('processor_key', sa.String(), nullable=False),
        sa.Column('processor_version', sa.String(), nullable=False),
        sa.Column('input_id', sa.String(length=16), nullable=True),
        sa.Column(
            'params',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'transform',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column(
            'data',
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb')
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), 'oracle')
            .with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('renditions_ready', sa.Boolean(), nullable=True),
        sa.Column(
            'state',
            sa.Enum('pending', 'running', 'ready', 'failed', name='versionstate', native_enum=False),
            nullable=False,
        ),
        sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['input_id'],
            ['page_versions.id'],
            name=op.f('fk_page_versions_input_id_page_versions'),
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['page_id'], ['pages.id'], name=op.f('fk_page_versions_page_id_pages'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_page_versions')),
    )
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_versions_page_id'), ['page_id', 'stage'], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_versions_page_id'))

    op.drop_table('page_versions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_cover_page_id_pages'), type_='foreignkey')

    op.drop_table('pages')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_project_id'))

    op.drop_table('scans')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_project_id'))
        batch_op.drop_index(batch_op.f('ix_sources_import_job_id'))

    op.drop_table('sources')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_updated_at'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_account_oauth_name'))
        batch_op.drop_index(batch_op.f('ix_oauth_account_account_id'))

    op.drop_table('oauth_account')
    with op.batch_alter_table('accesstoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accesstoken_created_at'))

    op.drop_table('accesstoken')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
