"""Link a recipe to its profile and keep the order mode of a profile.

Revision ID: d1bd087dadcc
Revises: 45e3f395141c
Create Date: 2026-10-04 09:00:49.570922
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'd1bd087dadcc'
down_revision: str | Sequence[str] | None = '45e3f395141c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'order',
                sa.Enum('usual', 'free', name='ordermode', native_enum=False),
                server_default='usual',
                nullable=False,
            )
        )

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_recipes_profile_id'), ['profile_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_recipes_profile_id_recipe_profiles'),
            'recipe_profiles',
            ['profile_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_profile_id_recipe_profiles'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_recipes_profile_id'))
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('recipe_profiles', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it.

    Nothing changes. No row says which profile a recipe was made from, since a recipe copied the steps of its profile
    and kept no reference, so the recipes that exist stay unlinked, and the profiles that exist start in the usual
    order, which the column defaults to.
    """


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
