"""Keep a project to one job writing page images.

The partial unique index ``ix_jobs_one_active_prepare`` keeps a project to one queued or running ``prepare-pages``
job, as autogenerate wrote it from the model, so two requests that both passed the check for an active job before
either committed cannot both store one, and two jobs never write the files of one page version together.

Revision ID: d5b4c3cd9379
Revises: 4f4f125a9583
Create Date: 2026-10-01 07:37:36.301404
"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'd5b4c3cd9379'
down_revision: str | Sequence[str] | None = '4f4f125a9583'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(
            'ix_jobs_one_active_prepare',
            ['project_id'],
            unique=True,
            sqlite_where=sa.text("kind = 'prepare-pages' AND state IN ('queued', 'running')"),
            postgresql_where=sa.text("kind = 'prepare-pages' AND state IN ('queued', 'running')"),
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(
            'ix_jobs_one_active_prepare',
            sqlite_where=sa.text("kind = 'prepare-pages' AND state IN ('queued', 'running')"),
            postgresql_where=sa.text("kind = 'prepare-pages' AND state IN ('queued', 'running')"),
        )

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
