"""Add the places accounts left books at.

Revision ID: d97b3f94c617
Revises: e2bfc43f17bc
Create Date: 2026-10-02 16:13:31.721631
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'd97b3f94c617'
down_revision: str | Sequence[str] | None = 'e2bfc43f17bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The identifier of an account, as the fastapi-users library declared it: CHAR(36) on SQLite and UUID on PostgreSQL
ACCOUNT_GUID = sa.CHAR(36).with_variant(postgresql.UUID(), 'postgresql')


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'book_places',
        sa.Column('account_id', ACCOUNT_GUID, nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('mode', sa.Enum('workspace', 'reading', name='placemode', native_enum=False), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('scan_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('source_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('view', sa.Enum('page', 'spread', 'grid', name='viewmode', native_enum=False), nullable=False),
        sa.Column('compare', sa.Enum('off', 'swipe', 'side', name='comparemode', native_enum=False), nullable=False),
        sa.Column(
            'filter', sa.Enum('all', 'check', 'left-out', 'wide', name='pagefilter', native_enum=False), nullable=False
        ),
        sa.Column('canvas_zoom', sa.Float(), nullable=True),
        sa.Column('canvas_centre_x', sa.Float(), nullable=True),
        sa.Column('canvas_centre_y', sa.Float(), nullable=True),
        sa.Column('strip_page_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
        sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_id'], ['user.id'], name=op.f('fk_book_places_account_id_user'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_book_places_project_id_projects'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('account_id', 'project_id', name=op.f('pk_book_places')),
    )
    with op.batch_alter_table('book_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_places_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_places_project_id'))

    op.drop_table('book_places')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
