"""Add the rules that send pages to recipes.

Revision ID: dc4a30549b71
Revises: d97b3f94c617
Create Date: 2026-10-02 19:29:32.326781
"""

import warnings
from typing import TYPE_CHECKING

import advanced_alchemy.types.guid
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ('data_downgrades', 'data_upgrades', 'downgrade', 'schema_downgrades', 'schema_upgrades', 'upgrade')

# Revision identifiers, used by Alembic
revision: str = 'dc4a30549b71'
down_revision: str | Sequence[str] | None = 'd97b3f94c617'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Change the schema, then the data, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    """Revert the data, then the schema, in the transaction of the migration, which commits or rolls back whole."""
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Change the schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recipe_rules',
        sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('project_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'import',
                'page-split',
                'page-order',
                'geometry',
                'cleanup',
                'layout',
                'background',
                'recognition',
                'proofreading',
                'typesetting',
                name='stage',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'condition',
            sa.Enum(
                'plates',
                'covers',
                'blanks',
                'illustrated',
                'odd',
                'even',
                'group',
                name='rulecondition',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('group_label', sa.String(), server_default='', nullable=False),
        sa.Column('recipe_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['projects.id'], name=op.f('fk_recipe_rules_project_id_projects'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_rules_recipe_id_recipes'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_rules')),
        sa.UniqueConstraint('project_id', 'stage', 'condition', 'group_label', name=op.f('uq_recipe_rules_project_id')),
    )
    with op.batch_alter_table('recipe_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_rules_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_rules_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('page_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_label', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Change the schema back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('group_label')

    with op.batch_alter_table('page_stages', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    with op.batch_alter_table('recipe_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_rules_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_rules_project_id'))

    op.drop_table('recipe_rules')
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Change the rows the schema change affects, after it."""


def data_downgrades() -> None:
    """Change the rows back, before the schema change is reverted."""
