// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountCreate
 *
 * Registration with an email address and a password; the account starts unverified.
 */
export type AccountCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * AccountRead
 *
 * The signed-in account.
 */
export type AccountRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * AccountUpdate
 *
 * A change to the signed-in account: its password.
 */
export type AccountUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * Body_auth_cookie_login_api_v1_auth_login_post
 */
export type BodyAuthCookieLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_reset_forgot_password_api_v1_auth_forgot_password_post
 */
export type BodyResetForgotPasswordApiV1AuthForgotPasswordPost = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_reset_reset_password_api_v1_auth_reset_password_post
 */
export type BodyResetResetPasswordApiV1AuthResetPasswordPost = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_verify_request_token_api_v1_auth_request_verify_token_post
 */
export type BodyVerifyRequestTokenApiV1AuthRequestVerifyTokenPost = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_verify_verify_api_v1_auth_verify_post
 */
export type BodyVerifyVerifyApiV1AuthVerifyPost = {
    /**
     * Token
     */
    token: string;
};

/**
 * BookDetailsSchema
 *
 * Bibliographic description of a book.
 *
 * :ivar title: Title of the book.
 * :ivar subtitle: Words of the title page that explain the title.
 * :ivar parallel_titles: Titles in other languages that the title page prints beside the title.
 * :ivar original_title: Title of the original work, for a translation.
 * :ivar contributors: People who made the book, each with a role, in the order of the title page.
 * :ivar primary_author: The first author, else the first contributor of any role, else an empty string.
 * :ivar publisher: Publisher of the book.
 * :ivar printer: Printing house.
 * :ivar publication_place: City of publication.
 * :ivar publication_year: Year of publication as printed.
 * :ivar edition: Edition statement.
 * :ivar censorship: Censor's permit printed in the book.
 * :ivar series: Series the book belongs to.
 * :ivar series_number: Number of the book in its series.
 * :ivar volume: Volume or part within a multi-volume work.
 * :ivar languages: ISO 639-3 codes of the languages of the text.
 * :ivar orthography: Spelling system of the print.
 * :ivar script: Writing system of the print.
 * :ivar printed_pagination: Pagination as a catalogue states it.
 * :ivar height_cm: Height of the book in centimetres, or None when unknown.
 * :ivar illustrations: Illustrations as a catalogue states them.
 * :ivar binding: Binding or cover of the copy.
 * :ivar identifiers: Numbers and addresses that identify the book or the copy, in normalized form.
 * :ivar subjects: Topics of the book.
 * :ivar rights: Whether the result of the work may be published.
 * :ivar copy_holder: Owner of the copy that was scanned.
 * :ivar copy_notes: Marks of the copy that was scanned.
 * :ivar notes: Free-form notes of the owner.
 */
export type BookDetailsSchema = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle: string;
    /**
     * Parallel Titles
     */
    parallel_titles: Array<string>;
    /**
     * Original Title
     */
    original_title: string;
    /**
     * Contributors
     */
    contributors: Array<ContributorSchema>;
    /**
     * Primary Author
     */
    primary_author: string;
    /**
     * Publisher
     */
    publisher: string;
    /**
     * Printer
     */
    printer: string;
    /**
     * Publication Place
     */
    publication_place: string;
    /**
     * Publication Year
     */
    publication_year: string;
    /**
     * Edition
     */
    edition: string;
    /**
     * Censorship
     */
    censorship: string;
    /**
     * Series
     */
    series: string;
    /**
     * Series Number
     */
    series_number: string;
    /**
     * Volume
     */
    volume: string;
    /**
     * Languages
     */
    languages: Array<string>;
    orthography: Orthography;
    script: Script;
    /**
     * Printed Pagination
     */
    printed_pagination: string;
    /**
     * Height Cm
     */
    height_cm: number | null;
    /**
     * Illustrations
     */
    illustrations: string;
    /**
     * Binding
     */
    binding: string;
    /**
     * Identifiers
     */
    identifiers: Array<IdentifierSchema>;
    /**
     * Subjects
     */
    subjects: Array<string>;
    rights: RightsStatus;
    /**
     * Copy Holder
     */
    copy_holder: string;
    /**
     * Copy Notes
     */
    copy_notes: string;
    /**
     * Notes
     */
    notes: string;
};

/**
 * ColorMode
 *
 * Colour depth of a page image as stored in the source.
 */
export type ColorMode = 'bilevel' | 'gray' | 'color' | 'unknown';

/**
 * ContributorRole
 *
 * Role of a person in the making of a book.
 *
 * The value of a member is its code in the `MARC Code List for Relators <https://www.loc.gov/marc/relators/>`_ and
 * the label is the term of that list, so an export to library formats writes the codes without a translation table.
 */
export type ContributorRole = 'aut' | 'edt' | 'com' | 'trl' | 'ill' | 'egr' | 'ltg' | 'pht' | 'wpr' | 'win' | 'ann' | 'cmm' | 'dte' | 'ctb' | 'oth';

/**
 * ContributorSchema
 *
 * A person who took part in the making of a book, with the role they had.
 *
 * :ivar name: Name as printed in the book.
 * :ivar role: Role of the person, a code of the MARC list of relators.
 */
export type ContributorSchema = {
    /**
     * Name
     */
    name: string;
    role: ContributorRole;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * FileType
 *
 * A file type accepted as a book source.
 */
export type FileType = 'pdf' | 'djvu' | 'tiff' | 'jpeg' | 'jpeg-2000' | 'png';

/**
 * RequestValidationError
 */
export type HttpValidationError = {
    /**
     * Problem title
     */
    title: string;
    /**
     * Problem type
     */
    type: string;
    /**
     * Status code
     */
    status: number;
    errors: Array<ValidationError>;
};

/**
 * IdentifierSchema
 *
 * A number or an address that identifies a book or a copy of it.
 *
 * :ivar scheme: Kind of the identifier.
 * :ivar value: The identifier in any spelling its scheme accepts, which the resource shows normalized.
 */
export type IdentifierSchema = {
    scheme: IdentifierScheme;
    /**
     * Value
     */
    value: string;
};

/**
 * IdentifierScheme
 *
 * Kind of number or address that identifies a book or one copy of it, each with its rule of writing.
 */
export type IdentifierScheme = 'isbn' | 'oclc' | 'lccn' | 'shelfmark' | 'url';

/**
 * ImagePathsSchema
 *
 * The images a scan or a page has once they are cut, each as the path of a file of the IIIF route.
 *
 * :ivar full: The image at its native resolution.
 * :ivar preview: The image shrunk to 2048 pixels on its longer side.
 * :ivar thumbnail: The image shrunk to a thumbnail.
 * :ivar iiif_info: The image information document of the tile pyramid, which a viewer reads to find the tiles.
 */
export type ImagePathsSchema = {
    /**
     * Full
     */
    full: string;
    /**
     * Preview
     */
    preview: string;
    /**
     * Thumbnail
     */
    thumbnail: string;
    /**
     * Iiif Info
     */
    iiif_info: string;
};

/**
 * ImagePolicy
 *
 * How a project stores the ``full`` image of its scans and page versions.
 *
 * A bilevel image is a lossless PNG under either policy. The policy decides only gray and colour images, and a change
 * applies to images written afterwards, so nothing stored is encoded again.
 */
export type ImagePolicy = 'compact' | 'lossless';

/**
 * ImportResultSchema
 *
 * What an import job did with the files of its upload.
 *
 * :ivar imported: Identifiers of the sources the job committed to the project, in book order.
 * :ivar rejected: Files no check let through, each with its reason.
 * :ivar skipped: Names of the files a cancelled job never reached.
 */
export type ImportResultSchema = {
    /**
     * Imported
     */
    imported: Array<string>;
    /**
     * Rejected
     */
    rejected: Array<RejectedFileSchema>;
    /**
     * Skipped
     */
    skipped: Array<string>;
};

/**
 * JobKind
 *
 * What a background job does.
 */
export type JobKind = 'import-source' | 'prepare-pages';

/**
 * JobSchema
 *
 * A background job, its state and its progress; also the data of a ``job-changed`` event.
 *
 * :ivar id: Identifier of the job.
 * :ivar project_id: Project the job works on.
 * :ivar kind: What the job does.
 * :ivar state: Where the job is in its life cycle.
 * :ivar progress: How many of its steps are done.
 * :ivar error: Why the job failed, shown to the user, or empty.
 * :ivar result: What an import job did with the files of its upload, or None until it has finished.
 * :ivar created_at: When the job was recorded.
 * :ivar started_at: When a worker started the job, or None while it is queued.
 * :ivar finished_at: When the job reached a final state, or None before.
 */
export type JobSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    kind: JobKind;
    state: JobState;
    progress: ProgressSchema;
    /**
     * Error
     */
    error: string;
    result: ImportResultSchema | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * JobState
 *
 * Lifecycle of a background job.
 */
export type JobState = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';

/**
 * LabelRange
 *
 * A range of pages to number, from one page to another in the order of the book.
 *
 * :ivar first_page_id: First page of the range.
 * :ivar last_page_id: Last page of the range, which may be the first page but not stand before it.
 * :ivar style: How the numbers are written; ``none`` erases the labels of the range.
 * :ivar start: Number of the first numbered page, from 1, and at most 3999 in a Roman style.
 * :ivar bracketed: Whether to enclose the label in square brackets.
 * :ivar skip_kinds: Kinds of page that take no number and keep their label, such as plates.
 */
export type LabelRange = {
    /**
     * First Page Id
     */
    first_page_id: string;
    /**
     * Last Page Id
     */
    last_page_id: string;
    style: LabelStyle;
    /**
     * Start
     */
    start?: number;
    /**
     * Bracketed
     */
    bracketed?: boolean;
    /**
     * Skip Kinds
     */
    skip_kinds?: Array<PageKind>;
};

/**
 * LabelStyle
 *
 * How the number of a page is written, which the numbering of a range of pages applies to its numbers.
 *
 * The domain imports only the standard library, so the Roman numerals are written here and not taken from the
 * ``roman`` package, whose one function would be about a dozen lines of ours.
 */
export type LabelStyle = 'arabic' | 'roman-lower' | 'roman-upper' | 'none';

/**
 * ManifestPage[PageSchema]
 */
export type ManifestPagePageSchema = {
    /**
     * Items
     */
    items: Array<PageSchema>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * MetadataSuggestionSchema
 *
 * Description fields found in a source; an empty string or list means nothing was found.
 *
 * :ivar title: Title found in the source.
 * :ivar contributors: People found in the source, each with the role the metadata gives them.
 * :ivar publisher: Publisher found in the source.
 * :ivar publication_year: Year of publication found in the source.
 * :ivar languages: ISO 639-3 codes of the languages found in the source.
 * :ivar identifiers: Valid ISBNs and web addresses found in the source.
 * :ivar subjects: Topics found in the source.
 */
export type MetadataSuggestionSchema = {
    /**
     * Title
     */
    title: string;
    /**
     * Contributors
     */
    contributors: Array<ContributorSchema>;
    /**
     * Publisher
     */
    publisher: string;
    /**
     * Publication Year
     */
    publication_year: string;
    /**
     * Languages
     */
    languages: Array<string>;
    /**
     * Identifiers
     */
    identifiers: Array<IdentifierSchema>;
    /**
     * Subjects
     */
    subjects: Array<string>;
};

/**
 * NewPageOrigin
 *
 * Where the image of a page the user adds comes from.
 *
 * Only a blank leaf and a placeholder are added by hand, since a page cut from a scan is made by the page split and
 * by binding a scan to a placeholder.
 */
export type NewPageOrigin = 'blank' | 'placeholder';

/**
 * Orthography
 *
 * Spelling norm of the printed text.
 */
export type Orthography = 'unknown' | 'pre-reform' | 'modern';

/**
 * PageAnchorBody
 *
 * A place in the book that the body has to name, by the page it lies before or after.
 */
export type PageAnchorBody = {
    /**
     * Before Page Id
     */
    before_page_id?: string | null;
    /**
     * After Page Id
     */
    after_page_id?: string | null;
};

/**
 * PageCreate
 *
 * A page to add without a scan: a placeholder that waits for one, or a generated blank leaf.
 *
 * The place is the page it lies before or after, and the end of the book when neither is given. A blank leaf has the
 * median size of the book's pages unless its size is given, in which case both sides are, and the resolution may be.
 *
 * :ivar origin: Whether the page is a blank leaf or a placeholder; a page from a scan is made by the split and by
 * binding a scan.
 * :ivar kind: Role of the page in the book.
 * :ivar label: Printed number of the page, or empty.
 * :ivar notes: Notes of the user.
 * :ivar width_px: Width of a blank leaf in pixels, given with its height.
 * :ivar height_px: Height of a blank leaf in pixels, given with its width.
 * :ivar dpi: Resolution of a blank leaf in dots per inch, given with its size.
 */
export type PageCreate = {
    /**
     * Before Page Id
     */
    before_page_id?: string | null;
    /**
     * After Page Id
     */
    after_page_id?: string | null;
    origin: NewPageOrigin;
    kind: PageKind;
    /**
     * Label
     */
    label?: string;
    /**
     * Notes
     */
    notes?: string;
    /**
     * Width Px
     */
    width_px?: number | null;
    /**
     * Height Px
     */
    height_px?: number | null;
    /**
     * Dpi
     */
    dpi?: number | null;
};

/**
 * PageKind
 *
 * Role of a page in the printed book.
 */
export type PageKind = 'cover' | 'back-cover' | 'endpaper' | 'frontispiece' | 'title' | 'text' | 'plate' | 'blank' | 'other';

/**
 * PageMove
 *
 * Where to put one page: before or after another page.
 */
export type PageMove = {
    /**
     * Before Page Id
     */
    before_page_id?: string | null;
    /**
     * After Page Id
     */
    after_page_id?: string | null;
};

/**
 * PageOrigin
 *
 * Where the image of a page comes from.
 */
export type PageOrigin = 'scan' | 'blank' | 'placeholder';

/**
 * PageSchema
 *
 * A page of a book.
 *
 * :ivar id: Identifier of the page, which stays the same when the page is moved.
 * :ivar position: Place of the page in the book from zero, counted over every page, excluded ones included, except
 * in a manifest listing only the included pages, which numbers those.
 * :ivar label: Printed number, such as ``xii`` or ``12``, or empty for an unnumbered page.
 * :ivar kind: Role of the page in the book.
 * :ivar origin: Where the image of the page comes from.
 * :ivar scan_id: Scan the page was cut from, or None for a blank leaf, a placeholder, or a page whose source was
 * deleted.
 * :ivar source_id: Source holding the page's scan, by which a client selects every page of one source, or None.
 * :ivar slot: Part of the scan the page shows: 0 the whole scan, 1 and 2 the halves of a spread.
 * :ivar included: Whether the page is part of the book.
 * :ivar notes: Notes of the user.
 * :ivar images: Paths of the images of the page's base version, or None while it has none.
 * :ivar created_at: When the page was created.
 * :ivar updated_at: When the page was last changed.
 */
export type PageSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Position
     */
    position: number;
    /**
     * Label
     */
    label: string;
    kind: PageKind;
    origin: PageOrigin;
    /**
     * Scan Id
     */
    scan_id: string | null;
    /**
     * Source Id
     */
    source_id: string | null;
    /**
     * Slot
     */
    slot: number;
    /**
     * Included
     */
    included: boolean;
    /**
     * Notes
     */
    notes: string;
    images: ImagePathsSchema | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PageUpdate
 *
 * A JSON Merge Patch of a page: an omitted field is kept, and a null label or note is cleared.
 *
 * The kind and the inclusion of a page have no empty value, so they may be omitted but not null.
 *
 * :ivar label: New printed number, or None to clear it.
 * :ivar kind: New role of the page in the book.
 * :ivar included: New decision whether the page is part of the book.
 * :ivar notes: New notes, or None to clear them.
 */
export type PageUpdate = {
    /**
     * Label
     */
    label?: string | null;
    /**
     * Kind
     */
    kind?: PageKind;
    /**
     * Included
     */
    included?: boolean;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * Page[ProjectSchema]
 */
export type PageProjectSchema = {
    /**
     * Items
     */
    items: Array<ProjectSchema>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * Page[ScanSchema]
 */
export type PageScanSchema = {
    /**
     * Items
     */
    items: Array<ScanSchema>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * Page[SourceSchema]
 */
export type PageSourceSchema = {
    /**
     * Items
     */
    items: Array<SourceSchema>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagesMove
 *
 * Where to put a group of pages, which keep their order in the book.
 *
 * :ivar page_ids: The pages to move, each at most once.
 */
export type PagesMove = {
    /**
     * Before Page Id
     */
    before_page_id?: string | null;
    /**
     * After Page Id
     */
    after_page_id?: string | null;
    /**
     * Page Ids
     */
    page_ids: Array<string>;
};

/**
 * ProgressSchema
 *
 * How far a job has come.
 *
 * :ivar done: Steps completed.
 * :ivar total: Steps in all, zero while unknown.
 * :ivar fraction: Completed share between 0 and 1, zero while the total is unknown.
 */
export type ProgressSchema = {
    /**
     * Done
     */
    done: number;
    /**
     * Total
     */
    total: number;
    /**
     * Fraction
     */
    fraction: number;
};

/**
 * ProjectCreate
 *
 * The description of a new book; only the title is required.
 *
 * :ivar title: Title of the book.
 * :ivar subtitle: Words of the title page that explain the title.
 * :ivar parallel_titles: Titles in other languages that the title page prints beside the title.
 * :ivar original_title: Title of the original work, for a translation.
 * :ivar contributors: People who made the book, each with a role, in the order of the title page.
 * :ivar publisher: Publisher of the book.
 * :ivar printer: Printing house.
 * :ivar publication_place: City of publication.
 * :ivar publication_year: Year of publication as printed, which may be a range or an estimate.
 * :ivar edition: Edition statement.
 * :ivar censorship: Censor's permit printed in the book.
 * :ivar series: Series the book belongs to.
 * :ivar series_number: Number of the book in its series.
 * :ivar volume: Volume or part within a multi-volume work.
 * :ivar languages: ISO 639-3 codes of the languages of the text.
 * :ivar orthography: Spelling system of the print.
 * :ivar script: Writing system of the print.
 * :ivar printed_pagination: Pagination as a catalogue states it.
 * :ivar height_cm: Height of the book in centimetres.
 * :ivar illustrations: Illustrations as a catalogue states them.
 * :ivar binding: Binding or cover of the copy.
 * :ivar identifiers: Numbers and addresses that identify the book or the copy.
 * :ivar subjects: Topics of the book.
 * :ivar rights: Whether the result of the work may be published.
 * :ivar copy_holder: Owner of the copy that was scanned.
 * :ivar copy_notes: Marks of the copy that was scanned.
 * :ivar notes: Free-form notes of the owner.
 */
export type ProjectCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Subtitle
     */
    subtitle?: string;
    /**
     * Parallel Titles
     */
    parallel_titles?: Array<string>;
    /**
     * Original Title
     */
    original_title?: string;
    /**
     * Contributors
     */
    contributors?: Array<ContributorSchema>;
    /**
     * Publisher
     */
    publisher?: string;
    /**
     * Printer
     */
    printer?: string;
    /**
     * Publication Place
     */
    publication_place?: string;
    /**
     * Publication Year
     */
    publication_year?: string;
    /**
     * Edition
     */
    edition?: string;
    /**
     * Censorship
     */
    censorship?: string;
    /**
     * Series
     */
    series?: string;
    /**
     * Series Number
     */
    series_number?: string;
    /**
     * Volume
     */
    volume?: string;
    /**
     * Languages
     */
    languages?: Array<string>;
    orthography?: Orthography;
    script?: Script;
    /**
     * Printed Pagination
     */
    printed_pagination?: string;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Illustrations
     */
    illustrations?: string;
    /**
     * Binding
     */
    binding?: string;
    /**
     * Identifiers
     */
    identifiers?: Array<IdentifierSchema>;
    /**
     * Subjects
     */
    subjects?: Array<string>;
    rights?: RightsStatus;
    /**
     * Copy Holder
     */
    copy_holder?: string;
    /**
     * Copy Notes
     */
    copy_notes?: string;
    /**
     * Notes
     */
    notes?: string;
};

/**
 * ProjectSchema
 *
 * A book being digitised.
 *
 * :ivar id: Identifier of the project.
 * :ivar details: Bibliographic description of the book.
 * :ivar image_policy: How the images of the project's scans and page versions are stored.
 * :ivar cover_page_id: Page whose thumbnail the project list shows, or None for the first page of the book.
 * :ivar page_count: Number of pages of the book, without the pages kept out of it.
 * :ivar source_count: Number of sources the book was assembled from.
 * :ivar scan_count: Number of scans in all the sources.
 * :ivar created_at: When the project was created.
 * :ivar updated_at: When the project was last changed.
 */
export type ProjectSchema = {
    /**
     * Id
     */
    id: string;
    details: BookDetailsSchema;
    image_policy: ImagePolicy;
    /**
     * Cover Page Id
     */
    cover_page_id: string | null;
    /**
     * Page Count
     */
    page_count: number;
    /**
     * Source Count
     */
    source_count: number;
    /**
     * Scan Count
     */
    scan_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 *
 * A JSON Merge Patch of a book description: an omitted field is kept and a null one is cleared.
 *
 * :ivar title: New title, which may be omitted but not null.
 * :ivar subtitle: New subtitle, or None to clear it.
 * :ivar parallel_titles: New titles in other languages, replacing the list, or None to empty it.
 * :ivar original_title: New title of the original work, or None to clear it.
 * :ivar contributors: New people who made the book, replacing the list, or None to empty it.
 * :ivar publisher: New publisher, or None to clear it.
 * :ivar printer: New printing house, or None to clear it.
 * :ivar publication_place: New city of publication, or None to clear it.
 * :ivar publication_year: New year of publication, or None to clear it.
 * :ivar edition: New edition statement, or None to clear it.
 * :ivar censorship: New censor's permit, or None to clear it.
 * :ivar series: New series, or None to clear it.
 * :ivar series_number: New number in the series, or None to clear it.
 * :ivar volume: New volume, or None to clear it.
 * :ivar languages: New ISO 639-3 codes, replacing the list, or None to empty it.
 * :ivar orthography: New orthography, or None to set it to unknown.
 * :ivar script: New writing system, or None to set it to unknown.
 * :ivar printed_pagination: New pagination, or None to clear it.
 * :ivar height_cm: New height in centimetres, or None to clear it.
 * :ivar illustrations: New statement of the illustrations, or None to clear it.
 * :ivar binding: New binding, or None to clear it.
 * :ivar identifiers: New identifiers, replacing the list, or None to empty it.
 * :ivar subjects: New topics, replacing the list, or None to empty it.
 * :ivar rights: New publishing rights, or None to set them to unknown.
 * :ivar copy_holder: New owner of the scanned copy, or None to clear it.
 * :ivar copy_notes: New marks of the scanned copy, or None to clear them.
 * :ivar notes: New notes, or None to clear them.
 * :ivar image_policy: New way to store the images of new scans and page versions, or None to set the default.
 * :ivar cover_page_id: New cover page, which must be a page of the project, or None to fall back to the first page.
 */
export type ProjectUpdate = {
    /**
     * Title
     */
    title?: string;
    /**
     * Subtitle
     */
    subtitle?: string | null;
    /**
     * Parallel Titles
     */
    parallel_titles?: Array<string> | null;
    /**
     * Original Title
     */
    original_title?: string | null;
    /**
     * Contributors
     */
    contributors?: Array<ContributorSchema> | null;
    /**
     * Publisher
     */
    publisher?: string | null;
    /**
     * Printer
     */
    printer?: string | null;
    /**
     * Publication Place
     */
    publication_place?: string | null;
    /**
     * Publication Year
     */
    publication_year?: string | null;
    /**
     * Edition
     */
    edition?: string | null;
    /**
     * Censorship
     */
    censorship?: string | null;
    /**
     * Series
     */
    series?: string | null;
    /**
     * Series Number
     */
    series_number?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
    /**
     * Languages
     */
    languages?: Array<string> | null;
    orthography?: Orthography | null;
    script?: Script | null;
    /**
     * Printed Pagination
     */
    printed_pagination?: string | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Illustrations
     */
    illustrations?: string | null;
    /**
     * Binding
     */
    binding?: string | null;
    /**
     * Identifiers
     */
    identifiers?: Array<IdentifierSchema> | null;
    /**
     * Subjects
     */
    subjects?: Array<string> | null;
    rights?: RightsStatus | null;
    /**
     * Copy Holder
     */
    copy_holder?: string | null;
    /**
     * Copy Notes
     */
    copy_notes?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    image_policy?: ImagePolicy | null;
    /**
     * Cover Page Id
     */
    cover_page_id?: string | null;
};

/**
 * RejectedFileSchema
 *
 * A file of an upload that was not imported, with the reason shown to the user.
 *
 * :ivar file_name: Name of the file, or of the main file of its source.
 * :ivar reason: Why the file was not imported.
 * :ivar detail: Text that says more than the reason, such as the name of the source the file repeats.
 */
export type RejectedFileSchema = {
    /**
     * File Name
     */
    file_name: string;
    reason: RejectionReason;
    /**
     * Detail
     */
    detail: string;
};

/**
 * RejectionReason
 *
 * Why one file of an upload was not imported, while the other files of the upload were.
 */
export type RejectionReason = 'duplicate' | 'unreadable' | 'unsupported-type' | 'system-file';

/**
 * RightsStatus
 *
 * Whether the result of the work on a book may be published.
 */
export type RightsStatus = 'unknown' | 'public-domain' | 'in-copyright';

/**
 * ScanAttach
 *
 * The scan to bind to a placeholder.
 *
 * :ivar scan_id: Scan to bind, which must be a scan of the project.
 * :ivar take_over: Whether to take the scan from the pages that show it already, such as the page the import made of
 * it, which deletes them.
 */
export type ScanAttach = {
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Take Over
     */
    take_over?: boolean;
};

/**
 * ScanFactsSchema
 *
 * Technical facts of one scan.
 *
 * :ivar width_px: Width of the image in pixels.
 * :ivar height_px: Height of the image in pixels.
 * :ivar color_mode: Whether the image is bilevel, gray or colour.
 * :ivar dpi_x: Horizontal resolution in dots per inch, or None when the source does not record it.
 * :ivar dpi_y: Vertical resolution in dots per inch, or None when the source does not record it.
 * :ivar bits_per_component: Bit depth of one colour component, or None when unknown.
 * :ivar image_format: Human name of the image format, such as ``JPEG`` or ``TIFF``.
 * :ivar width_mm: Physical width in millimetres, or None without a resolution.
 * :ivar height_mm: Physical height in millimetres, or None without a resolution.
 * :ivar has_text_layer: Whether the scan carries text, such as the OCR layer of a scanned PDF page.
 * :ivar extra: Further facts under the keys of the inspector that reported them.
 */
export type ScanFactsSchema = {
    /**
     * Width Px
     */
    width_px: number;
    /**
     * Height Px
     */
    height_px: number;
    color_mode: ColorMode;
    /**
     * Dpi X
     */
    dpi_x: number | null;
    /**
     * Dpi Y
     */
    dpi_y: number | null;
    /**
     * Bits Per Component
     */
    bits_per_component: number | null;
    /**
     * Image Format
     */
    image_format: string;
    /**
     * Width Mm
     */
    width_mm: number | null;
    /**
     * Height Mm
     */
    height_mm: number | null;
    /**
     * Has Text Layer
     */
    has_text_layer: boolean;
    /**
     * Extra
     */
    extra: {
        [key: string]: unknown;
    };
};

/**
 * ScanSchema
 *
 * One image of a source, as the file holds it.
 *
 * :ivar id: Identifier of the scan.
 * :ivar source_id: Source holding the scan.
 * :ivar number: Position of the scan in its source, starting at 0.
 * :ivar source_label: Page label the file itself gives, such as the PDF page label ``xii``, or empty.
 * :ivar facts: Technical facts of the image.
 * :ivar images: Paths of the derived images of the scan, or None until they are cut.
 */
export type ScanSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Number
     */
    number: number;
    /**
     * Source Label
     */
    source_label: string;
    facts: ScanFactsSchema;
    images: ImagePathsSchema | null;
};

/**
 * Script
 *
 * Writing system of the printed text, which is separate from its spelling norm.
 */
export type Script = 'unknown' | 'cyrillic' | 'latin' | 'mixed';

/**
 * SourceFileSchema
 *
 * One stored file of a source.
 *
 * :ivar name: Name of the file inside the source's directory.
 * :ivar size_bytes: Size of the file in bytes.
 * :ivar sha256: SHA-256 digest of the file's content as lower-case hexadecimal digits.
 */
export type SourceFileSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Sha256
     */
    sha256: string;
};

/**
 * SourceKind
 *
 * What one source of a book is, which selects the format that reads it.
 */
export type SourceKind = 'pdf' | 'djvu' | 'image';

/**
 * SourceSchema
 *
 * An uploaded file of a book, or the files of one indirect DjVu document, never changed after its import.
 *
 * :ivar id: Identifier of the source.
 * :ivar kind: Kind of the source, which selects the format that reads it.
 * :ivar file_type: Exact format of the main file.
 * :ivar file_name: Name the browser sent for the main file.
 * :ivar files: Stored files, the main file first; more than one only for an indirect DjVu document.
 * :ivar size_bytes: Total size of the files in bytes.
 * :ivar sha256: SHA-256 digest of the main file.
 * :ivar scan_count: Number of scans the source holds.
 * :ivar metadata: Technical metadata of the format, whose keys depend on the kind of source.
 * :ivar suggestion: Values of the book description found in the file.
 * :ivar import_job_id: Import job that created the source, or None once that job is deleted.
 * :ivar imported_at: When the source became part of the project.
 */
export type SourceSchema = {
    /**
     * Id
     */
    id: string;
    kind: SourceKind;
    file_type: FileType;
    /**
     * File Name
     */
    file_name: string;
    /**
     * Files
     */
    files: Array<SourceFileSchema>;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Scan Count
     */
    scan_count: number;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    suggestion: MetadataSuggestionSchema;
    /**
     * Import Job Id
     */
    import_job_id: string | null;
    /**
     * Imported At
     */
    imported_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Problem
 */
export type Problem = {
    /**
     * Problem title
     */
    title: string;
    /**
     * Problem type
     */
    type: string;
    /**
     * Status code
     */
    status: number;
    /**
     * Problem detail
     */
    detail?: string | null;
};

export type ListProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/v1/projects';
};

export type ListProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ListProjectsApiV1ProjectsGetError = ListProjectsApiV1ProjectsGetErrors[keyof ListProjectsApiV1ProjectsGetErrors];

export type ListProjectsApiV1ProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: PageProjectSchema;
};

export type ListProjectsApiV1ProjectsGetResponse = ListProjectsApiV1ProjectsGetResponses[keyof ListProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type CreateProjectApiV1ProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type CreateProjectApiV1ProjectsPostError = CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectSchema;
};

export type CreateProjectApiV1ProjectsPostResponse = CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type DeleteProjectApiV1ProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteError = DeleteProjectApiV1ProjectsProjectIdDeleteErrors[keyof DeleteProjectApiV1ProjectsProjectIdDeleteErrors];

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponse = DeleteProjectApiV1ProjectsProjectIdDeleteResponses[keyof DeleteProjectApiV1ProjectsProjectIdDeleteResponses];

export type ProjectApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ProjectApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ProjectApiV1ProjectsProjectIdGetError = ProjectApiV1ProjectsProjectIdGetErrors[keyof ProjectApiV1ProjectsProjectIdGetErrors];

export type ProjectApiV1ProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectSchema;
};

export type ProjectApiV1ProjectsProjectIdGetResponse = ProjectApiV1ProjectsProjectIdGetResponses[keyof ProjectApiV1ProjectsProjectIdGetResponses];

export type UpdateProjectApiV1ProjectsProjectIdPatchData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type UpdateProjectApiV1ProjectsProjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UpdateProjectApiV1ProjectsProjectIdPatchError = UpdateProjectApiV1ProjectsProjectIdPatchErrors[keyof UpdateProjectApiV1ProjectsProjectIdPatchErrors];

export type UpdateProjectApiV1ProjectsProjectIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectSchema;
};

export type UpdateProjectApiV1ProjectsProjectIdPatchResponse = UpdateProjectApiV1ProjectsProjectIdPatchResponses[keyof UpdateProjectApiV1ProjectsProjectIdPatchResponses];

export type ListSourcesApiV1ProjectsProjectIdSourcesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/v1/projects/{project_id}/sources';
};

export type ListSourcesApiV1ProjectsProjectIdSourcesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ListSourcesApiV1ProjectsProjectIdSourcesGetError = ListSourcesApiV1ProjectsProjectIdSourcesGetErrors[keyof ListSourcesApiV1ProjectsProjectIdSourcesGetErrors];

export type ListSourcesApiV1ProjectsProjectIdSourcesGetResponses = {
    /**
     * Successful Response
     */
    200: PageSourceSchema;
};

export type ListSourcesApiV1ProjectsProjectIdSourcesGetResponse = ListSourcesApiV1ProjectsProjectIdSourcesGetResponses[keyof ListSourcesApiV1ProjectsProjectIdSourcesGetResponses];

export type UploadSourcesApiV1ProjectsProjectIdSourcesPostData = {
    /**
     * UploadForm
     *
     * The form of an upload: the files to import, each one a source of its own.
     *
     * :ivar files: The uploaded files, at least one, from a directory or chosen one by one.
     */
    body: {
        /**
         * Files
         *
         * The files to import
         */
        files: Array<Blob | File>;
    };
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/sources';
};

export type UploadSourcesApiV1ProjectsProjectIdSourcesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UploadSourcesApiV1ProjectsProjectIdSourcesPostError = UploadSourcesApiV1ProjectsProjectIdSourcesPostErrors[keyof UploadSourcesApiV1ProjectsProjectIdSourcesPostErrors];

export type UploadSourcesApiV1ProjectsProjectIdSourcesPostResponses = {
    /**
     * Successful Response
     */
    202: JobSchema;
};

export type UploadSourcesApiV1ProjectsProjectIdSourcesPostResponse = UploadSourcesApiV1ProjectsProjectIdSourcesPostResponses[keyof UploadSourcesApiV1ProjectsProjectIdSourcesPostResponses];

export type DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Source Id
         *
         * Identifier of the source
         */
        source_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/sources/{source_id}';
};

export type DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteError = DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteErrors[keyof DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteErrors];

export type DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteResponse = DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteResponses[keyof DeleteSourceApiV1ProjectsProjectIdSourcesSourceIdDeleteResponses];

export type GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Source Id
         *
         * Identifier of the source
         */
        source_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/sources/{source_id}';
};

export type GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetError = GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetErrors[keyof GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetErrors];

export type GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetResponses = {
    /**
     * Successful Response
     */
    200: SourceSchema;
};

export type GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetResponse = GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetResponses[keyof GetSourceApiV1ProjectsProjectIdSourcesSourceIdGetResponses];

export type ListScansApiV1ProjectsProjectIdScansGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Source Id
         */
        source_id?: string | null;
    };
    url: '/api/v1/projects/{project_id}/scans';
};

export type ListScansApiV1ProjectsProjectIdScansGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ListScansApiV1ProjectsProjectIdScansGetError = ListScansApiV1ProjectsProjectIdScansGetErrors[keyof ListScansApiV1ProjectsProjectIdScansGetErrors];

export type ListScansApiV1ProjectsProjectIdScansGetResponses = {
    /**
     * Successful Response
     */
    200: PageScanSchema;
};

export type ListScansApiV1ProjectsProjectIdScansGetResponse = ListScansApiV1ProjectsProjectIdScansGetResponses[keyof ListScansApiV1ProjectsProjectIdScansGetResponses];

export type MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostData = {
    body: PageAnchorBody;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Source Id
         *
         * Identifier of the source
         */
        source_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/sources/{source_id}/pages/move';
};

export type MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostError = MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostErrors[keyof MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostErrors];

export type MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostResponse = MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostResponses[keyof MoveSourcePagesApiV1ProjectsProjectIdSourcesSourceIdPagesMovePostResponses];

export type ListPagesApiV1ProjectsProjectIdPagesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Included
         */
        included?: boolean;
    };
    url: '/api/v1/projects/{project_id}/pages';
};

export type ListPagesApiV1ProjectsProjectIdPagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ListPagesApiV1ProjectsProjectIdPagesGetError = ListPagesApiV1ProjectsProjectIdPagesGetErrors[keyof ListPagesApiV1ProjectsProjectIdPagesGetErrors];

export type ListPagesApiV1ProjectsProjectIdPagesGetResponses = {
    /**
     * Successful Response
     */
    200: ManifestPagePageSchema;
};

export type ListPagesApiV1ProjectsProjectIdPagesGetResponse = ListPagesApiV1ProjectsProjectIdPagesGetResponses[keyof ListPagesApiV1ProjectsProjectIdPagesGetResponses];

export type CreatePageApiV1ProjectsProjectIdPagesPostData = {
    body: PageCreate;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages';
};

export type CreatePageApiV1ProjectsProjectIdPagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type CreatePageApiV1ProjectsProjectIdPagesPostError = CreatePageApiV1ProjectsProjectIdPagesPostErrors[keyof CreatePageApiV1ProjectsProjectIdPagesPostErrors];

export type CreatePageApiV1ProjectsProjectIdPagesPostResponses = {
    /**
     * Successful Response
     */
    201: PageSchema;
};

export type CreatePageApiV1ProjectsProjectIdPagesPostResponse = CreatePageApiV1ProjectsProjectIdPagesPostResponses[keyof CreatePageApiV1ProjectsProjectIdPagesPostResponses];

export type DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Page Id
         *
         * Identifier of the page
         */
        page_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/{page_id}';
};

export type DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteError = DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteErrors[keyof DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteErrors];

export type DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteResponse = DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteResponses[keyof DeletePageApiV1ProjectsProjectIdPagesPageIdDeleteResponses];

export type PageApiV1ProjectsProjectIdPagesPageIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Page Id
         *
         * Identifier of the page
         */
        page_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/{page_id}';
};

export type PageApiV1ProjectsProjectIdPagesPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type PageApiV1ProjectsProjectIdPagesPageIdGetError = PageApiV1ProjectsProjectIdPagesPageIdGetErrors[keyof PageApiV1ProjectsProjectIdPagesPageIdGetErrors];

export type PageApiV1ProjectsProjectIdPagesPageIdGetResponses = {
    /**
     * Successful Response
     */
    200: PageSchema;
};

export type PageApiV1ProjectsProjectIdPagesPageIdGetResponse = PageApiV1ProjectsProjectIdPagesPageIdGetResponses[keyof PageApiV1ProjectsProjectIdPagesPageIdGetResponses];

export type UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchData = {
    body: PageUpdate;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Page Id
         *
         * Identifier of the page
         */
        page_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/{page_id}';
};

export type UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchError = UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchErrors[keyof UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchErrors];

export type UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PageSchema;
};

export type UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchResponse = UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchResponses[keyof UpdatePageApiV1ProjectsProjectIdPagesPageIdPatchResponses];

export type MovePageApiV1ProjectsProjectIdPagesPageIdMovePostData = {
    body: PageMove;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Page Id
         *
         * Identifier of the page
         */
        page_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/{page_id}/move';
};

export type MovePageApiV1ProjectsProjectIdPagesPageIdMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type MovePageApiV1ProjectsProjectIdPagesPageIdMovePostError = MovePageApiV1ProjectsProjectIdPagesPageIdMovePostErrors[keyof MovePageApiV1ProjectsProjectIdPagesPageIdMovePostErrors];

export type MovePageApiV1ProjectsProjectIdPagesPageIdMovePostResponses = {
    /**
     * Successful Response
     */
    200: PageSchema;
};

export type MovePageApiV1ProjectsProjectIdPagesPageIdMovePostResponse = MovePageApiV1ProjectsProjectIdPagesPageIdMovePostResponses[keyof MovePageApiV1ProjectsProjectIdPagesPageIdMovePostResponses];

export type MovePagesApiV1ProjectsProjectIdPagesMovePostData = {
    body: PagesMove;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/move';
};

export type MovePagesApiV1ProjectsProjectIdPagesMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type MovePagesApiV1ProjectsProjectIdPagesMovePostError = MovePagesApiV1ProjectsProjectIdPagesMovePostErrors[keyof MovePagesApiV1ProjectsProjectIdPagesMovePostErrors];

export type MovePagesApiV1ProjectsProjectIdPagesMovePostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MovePagesApiV1ProjectsProjectIdPagesMovePostResponse = MovePagesApiV1ProjectsProjectIdPagesMovePostResponses[keyof MovePagesApiV1ProjectsProjectIdPagesMovePostResponses];

export type NumberPagesApiV1ProjectsProjectIdPagesLabelsPostData = {
    body: LabelRange;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/labels';
};

export type NumberPagesApiV1ProjectsProjectIdPagesLabelsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type NumberPagesApiV1ProjectsProjectIdPagesLabelsPostError = NumberPagesApiV1ProjectsProjectIdPagesLabelsPostErrors[keyof NumberPagesApiV1ProjectsProjectIdPagesLabelsPostErrors];

export type NumberPagesApiV1ProjectsProjectIdPagesLabelsPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type NumberPagesApiV1ProjectsProjectIdPagesLabelsPostResponse = NumberPagesApiV1ProjectsProjectIdPagesLabelsPostResponses[keyof NumberPagesApiV1ProjectsProjectIdPagesLabelsPostResponses];

export type AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutData = {
    body: ScanAttach;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
        /**
         * Page Id
         *
         * Identifier of the page
         */
        page_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/pages/{page_id}/scan';
};

export type AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutError = AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutErrors[keyof AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutErrors];

export type AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutResponses = {
    /**
     * Successful Response
     */
    200: PageSchema;
};

export type AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutResponse = AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutResponses[keyof AttachScanApiV1ProjectsProjectIdPagesPageIdScanPutResponses];

export type CancelJobApiV1JobsJobIdDeleteData = {
    body?: never;
    path: {
        /**
         * Job Id
         *
         * Identifier of the job
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type CancelJobApiV1JobsJobIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type CancelJobApiV1JobsJobIdDeleteError = CancelJobApiV1JobsJobIdDeleteErrors[keyof CancelJobApiV1JobsJobIdDeleteErrors];

export type CancelJobApiV1JobsJobIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: JobSchema;
};

export type CancelJobApiV1JobsJobIdDeleteResponse = CancelJobApiV1JobsJobIdDeleteResponses[keyof CancelJobApiV1JobsJobIdDeleteResponses];

export type ReadJobApiV1JobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         *
         * Identifier of the job
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type ReadJobApiV1JobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ReadJobApiV1JobsJobIdGetError = ReadJobApiV1JobsJobIdGetErrors[keyof ReadJobApiV1JobsJobIdGetErrors];

export type ReadJobApiV1JobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobSchema;
};

export type ReadJobApiV1JobsJobIdGetResponse = ReadJobApiV1JobsJobIdGetResponses[keyof ReadJobApiV1JobsJobIdGetResponses];

export type ProjectEventsApiV1ProjectsProjectIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * Identifier of the project
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/events';
};

export type ProjectEventsApiV1ProjectsProjectIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ProjectEventsApiV1ProjectsProjectIdEventsGetError = ProjectEventsApiV1ProjectsProjectIdEventsGetErrors[keyof ProjectEventsApiV1ProjectsProjectIdEventsGetErrors];

export type ProjectEventsApiV1ProjectsProjectIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IiifFileApiV1IiifKeyGetData = {
    body?: never;
    path: {
        /**
         * Key
         *
         * Storage key of the file, as found in the image addresses of a page or a scan
         */
        key: string;
    };
    query?: never;
    url: '/api/v1/iiif/{key}';
};

export type IiifFileApiV1IiifKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type IiifFileApiV1IiifKeyGetError = IiifFileApiV1IiifKeyGetErrors[keyof IiifFileApiV1IiifKeyGetErrors];

export type IiifFileApiV1IiifKeyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthCookieLoginApiV1AuthLoginPostData = {
    body: BodyAuthCookieLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthCookieLoginApiV1AuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type AuthCookieLoginApiV1AuthLoginPostError = AuthCookieLoginApiV1AuthLoginPostErrors[keyof AuthCookieLoginApiV1AuthLoginPostErrors];

export type AuthCookieLoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLoginApiV1AuthLoginPostResponse = AuthCookieLoginApiV1AuthLoginPostResponses[keyof AuthCookieLoginApiV1AuthLoginPostResponses];

export type AuthCookieLogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthCookieLogoutApiV1AuthLogoutPostErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type AuthCookieLogoutApiV1AuthLogoutPostError = AuthCookieLogoutApiV1AuthLogoutPostErrors[keyof AuthCookieLogoutApiV1AuthLogoutPostErrors];

export type AuthCookieLogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLogoutApiV1AuthLogoutPostResponse = AuthCookieLogoutApiV1AuthLogoutPostResponses[keyof AuthCookieLogoutApiV1AuthLogoutPostResponses];

export type RegisterRegisterApiV1AuthRegisterPostData = {
    body: AccountCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterRegisterApiV1AuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type RegisterRegisterApiV1AuthRegisterPostError = RegisterRegisterApiV1AuthRegisterPostErrors[keyof RegisterRegisterApiV1AuthRegisterPostErrors];

export type RegisterRegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: AccountRead;
};

export type RegisterRegisterApiV1AuthRegisterPostResponse = RegisterRegisterApiV1AuthRegisterPostResponses[keyof RegisterRegisterApiV1AuthRegisterPostResponses];

export type VerifyRequestTokenApiV1AuthRequestVerifyTokenPostData = {
    body: BodyVerifyRequestTokenApiV1AuthRequestVerifyTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/request-verify-token';
};

export type VerifyRequestTokenApiV1AuthRequestVerifyTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type VerifyRequestTokenApiV1AuthRequestVerifyTokenPostError = VerifyRequestTokenApiV1AuthRequestVerifyTokenPostErrors[keyof VerifyRequestTokenApiV1AuthRequestVerifyTokenPostErrors];

export type VerifyRequestTokenApiV1AuthRequestVerifyTokenPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type VerifyVerifyApiV1AuthVerifyPostData = {
    body: BodyVerifyVerifyApiV1AuthVerifyPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type VerifyVerifyApiV1AuthVerifyPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type VerifyVerifyApiV1AuthVerifyPostError = VerifyVerifyApiV1AuthVerifyPostErrors[keyof VerifyVerifyApiV1AuthVerifyPostErrors];

export type VerifyVerifyApiV1AuthVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type VerifyVerifyApiV1AuthVerifyPostResponse = VerifyVerifyApiV1AuthVerifyPostResponses[keyof VerifyVerifyApiV1AuthVerifyPostResponses];

export type ResetForgotPasswordApiV1AuthForgotPasswordPostData = {
    body: BodyResetForgotPasswordApiV1AuthForgotPasswordPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type ResetForgotPasswordApiV1AuthForgotPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ResetForgotPasswordApiV1AuthForgotPasswordPostError = ResetForgotPasswordApiV1AuthForgotPasswordPostErrors[keyof ResetForgotPasswordApiV1AuthForgotPasswordPostErrors];

export type ResetForgotPasswordApiV1AuthForgotPasswordPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetResetPasswordApiV1AuthResetPasswordPostData = {
    body: BodyResetResetPasswordApiV1AuthResetPasswordPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type ResetResetPasswordApiV1AuthResetPasswordPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type ResetResetPasswordApiV1AuthResetPasswordPostError = ResetResetPasswordApiV1AuthResetPasswordPostErrors[keyof ResetResetPasswordApiV1AuthResetPasswordPostErrors];

export type ResetResetPasswordApiV1AuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersCurrentUserApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersCurrentUserApiV1UsersMeGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UsersCurrentUserApiV1UsersMeGetError = UsersCurrentUserApiV1UsersMeGetErrors[keyof UsersCurrentUserApiV1UsersMeGetErrors];

export type UsersCurrentUserApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type UsersCurrentUserApiV1UsersMeGetResponse = UsersCurrentUserApiV1UsersMeGetResponses[keyof UsersCurrentUserApiV1UsersMeGetResponses];

export type UsersPatchCurrentUserApiV1UsersMePatchData = {
    body: AccountUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersPatchCurrentUserApiV1UsersMePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UsersPatchCurrentUserApiV1UsersMePatchError = UsersPatchCurrentUserApiV1UsersMePatchErrors[keyof UsersPatchCurrentUserApiV1UsersMePatchErrors];

export type UsersPatchCurrentUserApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type UsersPatchCurrentUserApiV1UsersMePatchResponse = UsersPatchCurrentUserApiV1UsersMePatchResponses[keyof UsersPatchCurrentUserApiV1UsersMePatchResponses];

export type UsersDeleteUserApiV1UsersIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UsersDeleteUserApiV1UsersIdDeleteErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UsersDeleteUserApiV1UsersIdDeleteError = UsersDeleteUserApiV1UsersIdDeleteErrors[keyof UsersDeleteUserApiV1UsersIdDeleteErrors];

export type UsersDeleteUserApiV1UsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserApiV1UsersIdDeleteResponse = UsersDeleteUserApiV1UsersIdDeleteResponses[keyof UsersDeleteUserApiV1UsersIdDeleteResponses];

export type UsersUserApiV1UsersIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UsersUserApiV1UsersIdGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UsersUserApiV1UsersIdGetError = UsersUserApiV1UsersIdGetErrors[keyof UsersUserApiV1UsersIdGetErrors];

export type UsersUserApiV1UsersIdGetResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type UsersUserApiV1UsersIdGetResponse = UsersUserApiV1UsersIdGetResponses[keyof UsersUserApiV1UsersIdGetResponses];

export type UsersPatchUserApiV1UsersIdPatchData = {
    body: AccountUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UsersPatchUserApiV1UsersIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Client Error
     */
    '4XX': Problem;
    /**
     * Server Error
     */
    '5XX': Problem;
};

export type UsersPatchUserApiV1UsersIdPatchError = UsersPatchUserApiV1UsersIdPatchErrors[keyof UsersPatchUserApiV1UsersIdPatchErrors];

export type UsersPatchUserApiV1UsersIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type UsersPatchUserApiV1UsersIdPatchResponse = UsersPatchUserApiV1UsersIdPatchResponses[keyof UsersPatchUserApiV1UsersIdPatchResponses];
