"""The part of the interface of Doxa that the project uses, since the library ships no type information."""

from collections.abc import Mapping
from enum import Enum
from typing import Final

import numpy as np
from numpy.typing import NDArray

class Binarization:
    class Algorithms(Enum):
        OTSU = ...
        SAUVOLA = ...
        WOLF = ...
        ISAUVOLA = ...
        SU = ...
        GATOS = ...
        NICK = ...
        BRADLEY = ...

    def __init__(self, algorithm: Binarization.Algorithms) -> None: ...
    def initialize(self, image: NDArray[np.uint8], /) -> None: ...
    def to_binary(self, binary_image: NDArray[np.uint8], parameters: Mapping[str, int | float] = ...) -> None: ...

__version__: Final[str]
