"""Tests for the migrations, and for the application's refusal to start on a database they were not applied to.

The baseline builds the schema of the models, a migration keeps the rows of a book, and the application starts only
on a database at the head revision. Alembic runs every command in an event loop of its own, which ``env.py`` starts with ``asyncio.run``, so the tests
run commands in a worker thread through ``_migrate``.
"""

import json
import re
import shutil
from pathlib import Path
from typing import TYPE_CHECKING, Any, NamedTuple
from uuid import uuid4

import pytest
from advanced_alchemy.alembic.commands import AlembicCommands
from alembic.script import ScriptDirectory
from alembic.util import AutogenerateDiffsDetected
from asyncer import asyncify
from attrs import evolve
from delayed_assert import assert_expectations, expect
from sqlalchemy import func, inspect, select, text

from bookreviver.adapters.persistence.sqlalchemy.database import MIGRATIONS_DIR, SqlDatabase
from bookreviver.adapters.persistence.sqlalchemy.tables import (
    JobRow,
    PageRow,
    PageVersionRow,
    ProjectRow,
    ScanRow,
    SourceRow,
)
from bookreviver.adapters.persistence.sqlalchemy.unit_of_work import SqlAlchemyUnitOfWork
from bookreviver.app.container import build_container
from bookreviver.app.main import create_app
from bookreviver.app.providers.database import MIGRATE_COMMAND, MIGRATE_DOWNGRADE_COMMAND
from bookreviver.app.settings import PersistenceBackend
from tests.helpers.builders import EPOCH, make_job, make_page, make_page_version, make_project, make_scan, make_source
from tests.helpers.seeding import commit_account

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Callable

    from advanced_alchemy.base import CommonTableAttributes
    from dishka import AsyncContainer
    from sqlalchemy import TextClause

    from bookreviver.app.settings import Settings
    from bookreviver.domain.ids import ProjectId

pytestmark = pytest.mark.anyio

# The revision that describes a book in full, which replaces the columns ``authors`` and ``language``
DESCRIPTION_REVISION: str = '4f4f125a9583'
# Identifier and message of the revision a test adds after the head of the shipped migrations
TEST_REVISION: str = 'test_revision'
TEST_REVISION_MESSAGE: str = 'A revision a test adds after the baseline.'
# The line of script.py.mako that opens the body of schema_upgrades, after which a test writes its operations
SCHEMA_UPGRADES_DOCSTRING: str = '    """Change the schema to this revision."""'
# The column REBUILD_PROJECTS adds
REBUILT_COLUMN: str = 'probe'
# Adds a column to projects, which batch mode on SQLite does by copying, dropping and renaming the table
REBUILD_PROJECTS: str = f"""    with op.batch_alter_table('projects', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('{REBUILT_COLUMN}', sa.String(), nullable=False, server_default=''))"""
# Rebuilds projects, then deletes every project, which leaves the rows of its book pointing at no project while
# foreign keys are off, so the migration changes both the schema and the rows before its check fails
ORPHAN_THE_BOOK: str = f"{REBUILD_PROJECTS}\n    op.execute('DELETE FROM projects')"
# Changes the type of a column of projects, which only a comparison of types notices
RETYPE_A_COLUMN: str = """    with op.batch_alter_table('projects') as batch_op:
        batch_op.alter_column({column!r}, type_=sa.{new_type}())"""
# Changes nothing, standing for a revision of a branch that the checked-out code does not ship
NO_CHANGE: str = ''
# The tables holding the rows of a book, each of which refers to the project or to a row that does
BOOK_TABLES: tuple[type[CommonTableAttributes], ...] = (ProjectRow, SourceRow, ScanRow, PageRow, PageVersionRow, JobRow)


@pytest.fixture
async def fx_container(fx_settings: Settings) -> AsyncIterator[AsyncContainer]:
    """Yield the application's container on the SQL backend, with no schema created for it.

    :param fx_settings: Settings pointing at a fresh data directory of the test.
    :type fx_settings: Settings
    :returns: Iterator yielding the container and closing it afterwards.
    :rtype: AsyncIterator[AsyncContainer]
    """
    container = build_container(fx_settings.model_copy(update={'persistence': PersistenceBackend.SQLALCHEMY}))
    yield container
    await container.close()


@pytest.fixture
async def fx_empty_database(fx_settings: Settings) -> AsyncIterator[SqlDatabase]:
    """Open a database with no table, at the URL the settings name.

    :param fx_settings: Settings pointing at a fresh data directory of the test.
    :type fx_settings: Settings
    :returns: Iterator yielding the database and disposing of its engine afterwards.
    :rtype: AsyncIterator[SqlDatabase]
    """
    fx_settings.data_dir.mkdir(parents=True)
    database = SqlDatabase(fx_settings.resolved_database_url)
    yield database
    await database.dispose()


async def _migrate(database: SqlDatabase, command: Callable[..., None], *args: str) -> None:
    """Run an Alembic command in a worker thread, after closing the connections the test's event loop opened.

    :param database: Database the command runs on, whose pool is emptied first.
    :type database: SqlDatabase
    :param command: Command of ``AlembicCommands``, such as ``upgrade``.
    :type command: Callable[..., None]
    :param args: Arguments of the command, such as the target revision.
    :type args: str
    """
    await database.dispose()
    await asyncify(command)(*args)


async def _commit_book(database: SqlDatabase) -> ProjectId:
    """Commit a project whose cover is a page cut from a scan, with its source, the page's version and a job.

    :param database: Migrated database to commit into.
    :type database: SqlDatabase
    :returns: Identifier of the project.
    :rtype: ProjectId
    """
    project = make_project(owner_id=await commit_account(database))
    source = make_source(project_id=project.id)
    scan = make_scan(source=source, number=0)
    page = make_page(project_id=project.id, scan=scan)
    async with database.sessions() as session:
        uow = SqlAlchemyUnitOfWork(session)
        await uow.projects.add(project)
        await uow.sources.add(source)
        await uow.scans.add(scan)
        await uow.pages.add(page)
        await uow.page_versions.add(make_page_version(page_id=page.id))
        await uow.jobs.add(make_job(project_id=project.id))
        await uow.projects.update(evolve(project, cover_page_id=page.id))
        await uow.commit()
    return project.id


def _migrations_with_revision(database: SqlDatabase, target: Path, upgrade: str) -> AlembicCommands:
    """Copy the shipped migrations to ``target``, add a revision after their head, and point ``database`` at them.

    The revision is rendered from the shipped ``script.py.mako``, as ``make-migrations`` renders one, so the tests
    run a revision exactly as the template writes it, and ``upgrade`` fills its ``schema_upgrades``.

    :param database: Database whose configuration is pointed at the copied migrations.
    :type database: SqlDatabase
    :param target: Directory the migrations are copied to.
    :type target: Path
    :param upgrade: Indented body of the new revision's ``upgrade``.
    :type upgrade: str
    :returns: Alembic commands over the database and the copied migrations.
    :rtype: AlembicCommands
    """
    scripts = shutil.copytree(MIGRATIONS_DIR, target, ignore=shutil.ignore_patterns('__pycache__'))
    database.config.alembic_config.script_location = str(scripts)
    migrations = AlembicCommands(database.config)
    migrations.revision(message=TEST_REVISION_MESSAGE, rev_id=TEST_REVISION)
    revision = Path(ScriptDirectory(str(scripts)).get_revision(TEST_REVISION).path)
    source = revision.read_text(encoding='utf-8')
    filled = source.replace(SCHEMA_UPGRADES_DOCSTRING, f'{SCHEMA_UPGRADES_DOCSTRING}\n{upgrade}', 1)
    revision.write_text(filled, encoding='utf-8')
    return migrations


class TestBaseline:
    """Tests for the baseline revision, the one head of the shipped migrations."""

    def test_history_has_exactly_one_head(self) -> None:
        """Verify the migrations have one head, so ``upgrade head`` names one schema."""
        assert len(ScriptDirectory(str(MIGRATIONS_DIR)).get_heads()) == 1

    async def test_upgrade_and_downgrade_match_the_models(self, fx_empty_database: SqlDatabase) -> None:
        """Verify upgrading an empty database leaves nothing for autogenerate, and a downgrade and upgrade again too.

        ``alembic check`` raises when the database differs from the tables in any table, column, type, key or index.

        :param fx_empty_database: Database with no table.
        :type fx_empty_database: SqlDatabase
        """
        migrations = fx_empty_database.migrations
        await _migrate(fx_empty_database, migrations.upgrade, 'head')
        await _migrate(fx_empty_database, migrations.check)
        await _migrate(fx_empty_database, migrations.downgrade, 'base')
        async with fx_empty_database.engine.connect() as connection:
            left = await connection.run_sync(lambda sync_connection: inspect(sync_connection).get_table_names())
        await _migrate(fx_empty_database, migrations.upgrade, 'head')
        await _migrate(fx_empty_database, migrations.check)
        assert left == [fx_empty_database.config.alembic_config.version_table_name]


class TestDatabaseProvider:
    """Tests for DatabaseProvider.database, which opens the database only at the head revision."""

    async def test_refuses_a_database_no_revision_was_applied_to(self, fx_container: AsyncContainer) -> None:
        """Verify the application does not start on an unmigrated database and names the command that migrates it.

        :param fx_container: The application's container on the SQL backend, with no schema.
        :type fx_container: AsyncContainer
        """
        head = ScriptDirectory(str(MIGRATIONS_DIR)).get_current_head()
        expected = f'Database schema is at revision none, code expects {head}: run `{MIGRATE_COMMAND}`'
        with pytest.raises(RuntimeError, match=re.escape(expected)):
            await fx_container.get(SqlDatabase)

    async def test_refuses_a_database_migrated_by_code_it_does_not_ship(
        self, fx_container: AsyncContainer, fx_empty_database: SqlDatabase, tmp_path: Path
    ) -> None:
        """Verify a database migrated on another branch is refused with the downgrade that returns it, not an upgrade.

        ``upgrade head`` cannot help here: Alembic cannot locate the revision the database records.

        :param fx_container: The application's container on the SQL backend.
        :type fx_container: AsyncContainer
        :param fx_empty_database: The same database, which the test migrates with a revision the code does not ship.
        :type fx_empty_database: SqlDatabase
        :param tmp_path: Temporary directory of the test, holding the migrations of the other branch.
        :type tmp_path: Path
        """
        head = ScriptDirectory(str(MIGRATIONS_DIR)).get_current_head()
        branch = _migrations_with_revision(fx_empty_database, tmp_path / 'migrations', NO_CHANGE)
        await _migrate(fx_empty_database, branch.upgrade, 'head')
        expected = (
            f'Database schema is at revision {TEST_REVISION}, which this code does not ship, and code expects {head}: '
            f'run `{MIGRATE_DOWNGRADE_COMMAND} {head}` with the code that ships {TEST_REVISION}, '
            f'or restore the copy of the data directory made before migrating'
        )
        with pytest.raises(RuntimeError, match=re.escape(expected)):
            await fx_container.get(SqlDatabase)

    async def test_opens_a_database_at_the_head_revision(
        self, fx_container: AsyncContainer, fx_empty_database: SqlDatabase
    ) -> None:
        """Verify the application starts once the migrations are applied, and leaves the schema as they left it.

        :param fx_container: The application's container on the SQL backend.
        :type fx_container: AsyncContainer
        :param fx_empty_database: The same database, which the test migrates first.
        :type fx_empty_database: SqlDatabase
        """
        await _migrate(fx_empty_database, fx_empty_database.migrations.upgrade, 'head')
        database = await fx_container.get(SqlDatabase)
        assert (await database.schema_revisions()).is_current


class TestCreateApp:
    """Tests for the lifespan of the application create_app builds."""

    async def test_does_not_start_on_a_database_no_revision_was_applied_to(self, fx_settings: Settings) -> None:
        """Verify the application stops at start, before any request, when the database was never migrated.

        :param fx_settings: Settings pointing at a fresh data directory of the test.
        :type fx_settings: Settings
        """
        app = create_app(fx_settings)
        with pytest.raises(RuntimeError, match=re.escape(MIGRATE_COMMAND)):
            async with app.router.lifespan_context(app):
                pass


class TestEnv:
    """Tests for env.py, which runs a migration on SQLite with foreign keys off and checks them afterwards."""

    async def test_batch_rebuild_of_projects_keeps_the_rows_of_its_book(
        self, fx_empty_database: SqlDatabase, tmp_path: Path
    ) -> None:
        """Verify a revision rebuilding projects in batch mode leaves every row of the book and the project's cover.

        With foreign keys on, dropping the old projects table would cascade to the sources, scans, pages, versions
        and jobs.

        :param fx_empty_database: Database with no table.
        :type fx_empty_database: SqlDatabase
        :param tmp_path: Temporary directory of the test, holding the copied migrations.
        :type tmp_path: Path
        """
        await _migrate(fx_empty_database, fx_empty_database.migrations.upgrade, 'head')
        project_id = await _commit_book(fx_empty_database)
        migrations = _migrations_with_revision(fx_empty_database, tmp_path / 'migrations', REBUILD_PROJECTS)
        await _migrate(fx_empty_database, migrations.upgrade, 'head')
        async with fx_empty_database.sessions() as session:
            for table in BOOK_TABLES:
                expect(await session.scalar(select(func.count()).select_from(table)) == 1, table.__tablename__)
            cover_page_id = await session.scalar(select(ProjectRow.cover_page_id).where(ProjectRow.id == project_id))
        expect(cover_page_id is not None)
        assert_expectations()

    async def test_rows_left_without_their_project_roll_the_migration_back(
        self, fx_empty_database: SqlDatabase, tmp_path: Path
    ) -> None:
        """Verify a revision orphaning the rows of a book fails, and leaves the schema, rows and revision it found.

        The revision rebuilds projects and then deletes them, so both its schema change and its row change have to
        be undone, and the database must stay at the baseline for the application to refuse it.

        :param fx_empty_database: Database with no table.
        :type fx_empty_database: SqlDatabase
        :param tmp_path: Temporary directory of the test, holding the copied migrations.
        :type tmp_path: Path
        """
        await _migrate(fx_empty_database, fx_empty_database.migrations.upgrade, 'head')
        await _commit_book(fx_empty_database)
        baseline = await fx_empty_database.schema_revisions()
        migrations = _migrations_with_revision(fx_empty_database, tmp_path / 'migrations', ORPHAN_THE_BOOK)
        with pytest.raises(RuntimeError, match='foreign key to no row'):
            await _migrate(fx_empty_database, migrations.upgrade, 'head')
        async with fx_empty_database.sessions() as session:
            for table in BOOK_TABLES:
                expect(await session.scalar(select(func.count()).select_from(table)) == 1, table.__tablename__)
        async with fx_empty_database.engine.connect() as connection:
            columns = await connection.run_sync(lambda sync: inspect(sync).get_columns(ProjectRow.__tablename__))
        expect(REBUILT_COLUMN not in {column['name'] for column in columns})
        expect((await fx_empty_database.schema_revisions()).database == baseline.database)
        assert_expectations()

    @pytest.mark.parametrize(
        ('column', 'new_type'),
        [
            pytest.param('title', 'Integer', id='string-reflected-by-name'),
            pytest.param('cover_page_id', 'String', id='guid-compared-by-affinity'),
        ],
    )
    async def test_check_notices_a_column_whose_type_differs_from_the_tables(
        self, fx_empty_database: SqlDatabase, tmp_path: Path, column: str, new_type: str
    ) -> None:
        """Verify ``alembic check`` fails on a column of another type, so autogenerate writes type changes too.

        ``title`` has a type SQLite reflects by name, and ``cover_page_id`` a ``GUID`` it reflects by affinity.

        :param fx_empty_database: Database with no table.
        :type fx_empty_database: SqlDatabase
        :param tmp_path: Temporary directory of the test, holding the copied migrations.
        :type tmp_path: Path
        :param column: Column of projects whose type the revision changes.
        :type column: str
        :param new_type: SQLAlchemy type the revision gives the column.
        :type new_type: str
        """
        retype = RETYPE_A_COLUMN.format(column=column, new_type=new_type)
        migrations = _migrations_with_revision(fx_empty_database, tmp_path / 'migrations', retype)
        await _migrate(fx_empty_database, migrations.upgrade, 'head')
        with pytest.raises(AutogenerateDiffsDetected, match='modify_type'):
            await _migrate(fx_empty_database, migrations.check)


class OldProject(NamedTuple):
    """A project row as the revision before the extended description stored it.

    :ivar title: Title of the book, which names the row.
    :ivar authors: The single string of authors.
    :ivar language: The single string of the language.
    :ivar notes: Notes of the owner.
    """

    title: str
    authors: str
    language: str
    notes: str


class NewProject(NamedTuple):
    """The columns of the extended description a project row is expected to hold after the revision.

    :ivar title: Title of the book, which names the row.
    :ivar contributors: Contributors as stored JSON.
    :ivar languages: Languages as stored JSON.
    :ivar notes: Notes of the owner.
    """

    title: str
    contributors: list[dict[str, str]]
    languages: list[str]
    notes: str


OLD_PROJECTS: list[OldProject] = [
    OldProject('Both', 'Я. Карскі', 'bel', 'Kept'),
    OldProject('Named language', '', 'Belarusian', 'Kept'),
    OldProject('Named language without notes', '', 'Old Slavonic', ''),
    OldProject('Empty', '', '', ''),
]
NEW_PROJECTS: list[NewProject] = [
    NewProject('Both', [{'name': 'Я. Карскі', 'role': 'aut'}], ['bel'], 'Kept'),
    NewProject('Empty', [], [], ''),
    NewProject('Named language', [], [], 'Kept\nLanguage: Belarusian'),
    NewProject('Named language without notes', [], [], 'Language: Old Slavonic'),
]
INSERT_OLD_PROJECT: TextClause = text(
    'INSERT INTO projects (id, owner_id, title, authors, publisher, publication_place, publication_year, edition,'
    ' series, volume, language, orthography, notes, image_policy, created_at, updated_at)'
    " VALUES (:id, :owner_id, :title, :authors, '', '', '', '', '', '', :language, 'unknown', :notes, 'compact',"
    ' :moment, :moment)'
)
OLD_SUGGESTIONS: list[dict[str, str]] = [
    {'title': 'A', 'authors': 'Я. Карскі', 'publisher': 'P', 'publication_year': '1905', 'language': 'bel'},
    {'title': 'B', 'authors': '', 'publisher': '', 'publication_year': '', 'language': 'Belarusian'},
]
NEW_SUGGESTIONS: list[dict[str, Any]] = [
    {
        'title': 'A',
        'contributors': [{'name': 'Я. Карскі', 'role': 'aut'}],
        'publisher': 'P',
        'publication_year': '1905',
        'languages': ['bel'],
        'identifiers': [],
        'subjects': [],
    },
    {
        'title': 'B',
        'contributors': [],
        'publisher': '',
        'publication_year': '',
        'languages': [],
        'identifiers': [],
        'subjects': [],
    },
]
# A suggestion that lost its language name keeps no trace of it when it is turned back
OLD_SUGGESTIONS_AFTER_DOWNGRADE: list[dict[str, str]] = [OLD_SUGGESTIONS[0], {**OLD_SUGGESTIONS[1], 'language': ''}]
INSERT_OLD_SOURCE: TextClause = text(
    'INSERT INTO sources (id, project_id, kind, file_type, file_name, files, size_bytes, sha256, scan_count,'
    ' metadata, suggestion, import_job_id, imported_at)'
    " VALUES (:id, :project_id, 'pdf', 'pdf', :file_name, '[]', 0, :sha256, 0, '{}', :suggestion, NULL, :moment)"
)
SELECT_SUGGESTIONS: TextClause = text('SELECT suggestion FROM sources ORDER BY file_name')
SELECT_NEW_PROJECTS: TextClause = text('SELECT title, contributors, languages, notes FROM projects ORDER BY title')
SELECT_OLD_PROJECTS: TextClause = text('SELECT title, authors, language FROM projects ORDER BY title')


class TestDescriptionRevision:
    """Tests for the revision that describes a book in full."""

    async def test_moves_authors_and_language_into_the_new_columns_and_back(
        self, fx_empty_database: SqlDatabase
    ) -> None:
        """Verify the upgrade keeps every author and language, and the downgrade rebuilds the two old columns.

        A language that is a three-letter code becomes a language, any other value is appended to the notes, and an
        author becomes a contributor with the role ``aut``.

        :param fx_empty_database: Database with no table.
        :type fx_empty_database: SqlDatabase
        """
        migrations = fx_empty_database.migrations
        previous = ScriptDirectory(str(MIGRATIONS_DIR)).get_revision(DESCRIPTION_REVISION).down_revision
        await _migrate(fx_empty_database, migrations.upgrade, str(previous))
        owner_id = await commit_account(fx_empty_database)
        async with fx_empty_database.sessions() as session:
            for old in OLD_PROJECTS:
                await session.execute(
                    INSERT_OLD_PROJECT,
                    {'id': uuid4().bytes, 'owner_id': str(owner_id), 'moment': EPOCH, **old._asdict()},
                )
            await session.commit()

        await _migrate(fx_empty_database, migrations.upgrade, DESCRIPTION_REVISION)
        async with fx_empty_database.sessions() as session:
            upgraded = [
                NewProject(title, json.loads(contributors), json.loads(languages), notes)
                for title, contributors, languages, notes in await session.execute(SELECT_NEW_PROJECTS)
            ]
        await _migrate(fx_empty_database, migrations.downgrade, str(previous))
        async with fx_empty_database.sessions() as session:
            downgraded = [tuple(row) for row in await session.execute(SELECT_OLD_PROJECTS)]

        expect(upgraded == NEW_PROJECTS)
        expect(
            downgraded
            == [
                ('Both', 'Я. Карскі', 'bel'),
                ('Empty', '', ''),
                ('Named language', '', ''),
                ('Named language without notes', '', ''),
            ]
        )
        assert_expectations()

    async def test_moves_the_suggestion_of_a_source_into_the_new_shape_and_back(
        self, fx_empty_database: SqlDatabase
    ) -> None:
        """Verify a stored suggestion gets contributors and languages, and the downgrade restores the old keys.

        A suggestion with an author and a language code keeps both, and one whose language is a name loses it, since
        a suggestion is offered and not entered by the owner.

        :param fx_empty_database: Database with no table.
        :type fx_empty_database: SqlDatabase
        """
        migrations = fx_empty_database.migrations
        previous = ScriptDirectory(str(MIGRATIONS_DIR)).get_revision(DESCRIPTION_REVISION).down_revision
        await _migrate(fx_empty_database, migrations.upgrade, str(previous))
        project_id = uuid4().bytes
        async with fx_empty_database.sessions() as session:
            await session.execute(
                INSERT_OLD_PROJECT,
                {
                    'id': project_id,
                    'owner_id': str(await commit_account(fx_empty_database)),
                    'moment': EPOCH,
                    **OLD_PROJECTS[0]._asdict(),
                },
            )
            for position, suggestion in enumerate(OLD_SUGGESTIONS):
                await session.execute(
                    INSERT_OLD_SOURCE,
                    {
                        'id': uuid4().bytes,
                        'project_id': project_id,
                        'file_name': f'{position}.pdf',
                        'sha256': str(position) * 64,
                        'moment': EPOCH,
                        'suggestion': json.dumps(suggestion),
                    },
                )
            await session.commit()

        await _migrate(fx_empty_database, migrations.upgrade, DESCRIPTION_REVISION)
        async with fx_empty_database.sessions() as session:
            upgraded = [json.loads(row[0]) for row in await session.execute(SELECT_SUGGESTIONS)]
        await _migrate(fx_empty_database, migrations.downgrade, str(previous))
        async with fx_empty_database.sessions() as session:
            downgraded = [json.loads(row[0]) for row in await session.execute(SELECT_SUGGESTIONS)]

        expect(upgraded == NEW_SUGGESTIONS)
        expect(downgraded == OLD_SUGGESTIONS_AFTER_DOWNGRADE)
        assert_expectations()
